### ISSUE TITLE
TODOs

### ISSUE THREAD

**Issue by KFlash** [meriyah/meriyah#1]
Things needing finished:

- [x] (Parser) Label tracking
- [ ] (Parser) Lexical scope
- [x] (Parser) Location tracking
- [x] (Parser) Cover all edge cases
- [x] (Parser) Import error reporting code from private code

**Comment by KFlash** [comment]
The bullet list above is what's coming next, but for now I'm focusing on this bullets due to the complexity of this parser. 

- [ ] Fail & pass 100% acc. the specs
- [ ]  Cover all edge cases
- [ ] Simplify the bit masks and optimize

**Comment by KFlash** [comment]
**Note:** At this stage all edge cases seems to have been covered, and the parser passes all stress tests and the fuzzers I'm using, so I'm now soon going to move on to the next step.

**Comment by KFlash** [comment]
**Update:** Location tracking in progress!. First to land will be ranges, but tricky to implement so will take a few days.

**Comment by KFlash** [comment]
Location tracking is WIP ATM, and first to land within a few days will be ranges. Start and end values on the node. Note  that whatever I do the performance will drop. 

**Benchmark results without ranges:**

![withoutloc](https://user-images.githubusercontent.com/31855118/58442315-b5c27c00-811c-11e9-8e24-2da3c366e227.png)

**Benchmark results with  ranges:**

![withloc](https://user-images.githubusercontent.com/31855118/58442322-c70b8880-811c-11e9-8ef5-9b0d0d9f6eda.png)

@nchanged Thoughts?

**Comment by KFlash** [comment]
Lexical scope is on hole for now. Not sure if I'm going to do this inline or what...  So closing.

**Comment by KFlash** [comment]
Lexical binding and scope tracking have been implemented and can be enabled with the new `lexical` flag.

**Comment by 3cp** [comment]
@KFlash any doc on how to use `lexical` flag? I tried to turn it on in the demo https://meriyah.github.io/meriyah/ but the output didn't change.

**Comment by KFlash** [comment]
@3cp It only turns on lexical. Find duplicates like `function x(a, a) {}` will fail.
