### ISSUE TITLE
Performance comparison

### ISSUE THREAD

**Issue by arv** [meriyah/meriyah#10]
The claim that this is focused on performance is not backed by numbers. Maybe add a some performance tests and numbers

**Comment by aladdin-add** [comment]
Yeah It's just on the way! 👍

**Comment by KFlash** [comment]
@aladdin-add you can find the old benchmark [here](https://meriyah.github.io/meriyah/performance/), but in Meriyah the performance depends on the option you set and it's not adjusted so I didn't make the URL public .

And also a new REPL will be launched either today or tomorrow

**Comment by KFlash** [comment]
@aladdin-add Any progress on this?

@arv Just note this parser also are optimized for parsing large files. 5 MB or more. And uses less memory. That can't be shown in any benchmarks.

However if you try to parse `TSServer` (7 MB) with `ASTExplorer` the entire browser "snap" and you need to refresh. And if you try it with the [Esprima REPL](http://esprima.org/demo/parse.html) you can't even paste in that code. So you can't parse it at all.

Meriyah's REPL will soon be online, and it will only take you around a second to parse the entire code and your will end up with an AST with `1958838` lines.

I didn't find larger files at the moment, but should't be a problem either.

**Comment by KFlash** [comment]
@aladdin-add I added a link to the old benchmark in [meriyah REPL](https://meriyah.github.io/meriyah/). You can tweak and update the design on that one?

Closing this now as solved.
