### ISSUE TITLE
Expression after do/while

### ISSUE THREAD

**Issue by neumatho** [meriyah/meriyah#102]
Hi,

The following statement cannot be parsed in Meriyah, while both Acorn and Esprima parses it without problems.

`{ do { } while (false) false }`

Here is the result from Acorn which should be returned:

```
{
  "type": "Program",
  "start": 0,
  "end": 30,
  "body": [
    {
      "type": "BlockStatement",
      "start": 0,
      "end": 30,
      "body": [
        {
          "type": "DoWhileStatement",
          "start": 2,
          "end": 22,
          "body": {
            "type": "BlockStatement",
            "start": 5,
            "end": 8,
            "body": []
          },
          "test": {
            "type": "Literal",
            "start": 16,
            "end": 21,
            "value": false,
            "raw": "false"
          }
        },
        {
          "type": "ExpressionStatement",
          "start": 23,
          "end": 28,
          "expression": {
            "type": "Literal",
            "start": 23,
            "end": 28,
            "value": false,
            "raw": "false"
          }
        }
      ]
    }
  ],
  "sourceType": "module"
}
```

-Thomas

**Comment by 3cp** [comment]
@KFlash I saw in meriyah code, it referenced ECMA-262, section 7.9, page 21.
But it's currently in a different section of ECMA.
This is probably new in the standard? http://www.ecma-international.org/ecma-262/11.0/index.html#sec-automatic-semicolon-insertion

> The previous token is ) and the inserted semicolon would then be parsed as the terminating semicolon of a do-while statement (13.7.2).

**Comment by 3cp** [comment]
nvm @KFlash I saw our code uses OptionsSpecDeviation to force the semicolon here.

**Comment by 3cp** [comment]
@KFlash sorry, we didn't force it. I will add the missing implementation for the spec.

> The previous token is ) and the inserted semicolon would then be parsed as the terminating semicolon of a do-while statement (13.7.2).
