### ISSUE TITLE
Single line comment with new line

### ISSUE THREAD

**Issue by neumatho** [meriyah/meriyah#103]
If you have a single line comment which ends with a new line, the new line is included in the value in the collecting list.

```
var meriyah = require("meriyah")

var merComments = [];
meriyah.parse('//123\n', { onComment: merComments });
```

It is the value property in merComments. It should only be "123", but as you can see, it includes the new-line character as well:

```
Array (1 item)
  0: Object
    type: "SingleLine"
    value: "123\n"
```

Both Esprima and Acorn does not include the new-line.

-Thomas

**Comment by 3cp** [comment]
closed by #112
