### ISSUE TITLE
Wrong `TemplateElement` value

### ISSUE THREAD

**Issue by fisker** [meriyah/meriyah#109]
```js
require('meriyah').parse('tagA`a`\ntagB`b`', {ranges: true, loc: true}).body[0].expression.quasi.quasis[0].value
{ cooked: 'tagB', raw: 'a' }
```

`Node.value.cooked` should be `a`

**Comment by 3cp** [comment]
@KFlash where can I find the spec for "cooked"?

In estree spec repo, I can only find
> If the template literal is tagged and the text has an invalid escape, cooked will be null, e.g., tag`\unicode and \u{55}`

**Comment by KFlash** [comment]
That's the problem with ESTree. See the specs. All invalid tagged template should be null. All other values should be as they are without the tick and non-escapes. Example '0x65' should be latter a (*cooked*). Else it's raw
