### ISSUE TITLE
tslint => eslint

### ISSUE THREAD

**Issue by aladdin-add** [meriyah/meriyah#12]
refs: https://eslint.org/blog/2019/01/future-typescript-eslint

**Comment by KFlash** [comment]
@aladdin-add I did read the blog post, but I still think that TS parser will be very slow the way they doing it, but it's a step in right direction.

Seen the [Meriyah TypeScript parser repo](https://github.com/meriyah/meriyah-ts) ?

**Comment by aladdin-add** [comment]
is it available atm?
hopefully we can replace `@typescript-eslint/parser` to `meriyah-ts` in our codebase, dogfooding  :tada

**Comment by KFlash** [comment]
Not done **yet**. It's my next retirement project. For now it only does javascript parsing, but I started to get it to accept TypeScript syntax now.
