### ISSUE TITLE
Avoid parsing decorators without flag

### ISSUE THREAD

**Issue by KFlash** [meriyah/meriyah#120]
See this line https://github.com/meriyah/meriyah/blob/master/src/parser.ts#L423

Should not be parsed if the option flag isn't set for it.

Line 424 . What it checks? If for export, it's faster to set it in the end of the switch statement to avoid checking if export keyword exist. If that again trigger something regarding class, pass a param alongside or do the same for class. That way no need for duplicate check when already in a switch

**Comment by 3cp** [comment]
The check is moved to `parseDecorators` in order to avoid some repeated checks before few `parseDecorators` calls.

Yes, checking after switch can remove many checks in parseExportDeclaration and parseClassDeclaration.
