### ISSUE TITLE
Question: decorator before export has different location with `babel`

### ISSUE THREAD

**Issue by fisker** [meriyah/meriyah#124]
```js
require("meriyah").parse('@decorator export class Bar {}', {loc: true, module: true, next: true}).body[0]
{
  type: 'ExportNamedDeclaration',
  declaration: {
    type: 'ClassDeclaration',
    id: { type: 'Identifier', name: 'Bar', loc: [Object] },
    superClass: null,
    decorators: [ [Object] ],
    body: { type: 'ClassBody', body: [], loc: [Object] },
    loc: { start: [Object], end: [Object] }
  },
  specifiers: [],
  source: null,
  loc: { start: { line: 1, column: 0 }, end: { line: 1, column: 30 } }
}
```

We have column `0 ~ 30`

While `@babel/parser` has column `11 ~ 30`

```js
require("@babel/parser").parse('@decorator export class Bar {}', {sourceType:'module', plugins:[['decorators', {decoratorsBeforeExport: true}]]}).program.body[0].loc
SourceLocation {
  start: Position { line: 1, column: 11 },
  end: Position { line: 1, column: 30 },
  filename: undefined,
  identifierName: undefined
}
```

Should we align with them?

**Comment by 3cp** [comment]
I am not very sure babel's way is right, babel did not count the decorator as part of the ExportNamedDeclaration. This is kind of grey area since decorator is not in the ecma spec yet. cc @KFlash 

BTW, the decorators-legacy returns same result.
```js
require("@babel/parser").parse('@decorator export class Bar {}', {sourceType:'module', plugins:['decorators-legacy']}).program.body[0].loc
SourceLocation {
  start: Position { line: 1, column: 11 },
  end: Position { line: 1, column: 30 },
  filename: undefined,
  identifierName: undefined
}
```

**Comment by 3cp** [comment]
In ecma, this whole statement `@decorator export class Bar {}` is called a module item. It feels nature for it starting at column 0?

**Comment by 3cp** [comment]
Few other parsers are same as babel, I guess I need to fix ours.

**Comment by fisker** [comment]
That would be great!

**Comment by KFlash** [comment]
@fisker Out of curiosity. What kind of project do you use Meriyah? Simple parsing, or heavy parsing? 我只是古玩。

@3cp Nothing in the experimental folder in ESTree repo, or any PR for this?

**Comment by fisker** [comment]
I'm implementing meriyah support for prettier https://github.com/fisker/prettier/pull/685

**Comment by KFlash** [comment]
Interesting! And I worked in Hong Kong for 7 years and I only head mandaring all the time, so I guess different dialects, and I starting to be rusty. Better in speaking it rather than writing it :)
