### ISSUE TITLE
Wrong location for empty inline comment `//`

### ISSUE THREAD

**Issue by fisker** [meriyah/meriyah#126]
```js
require("meriyah").parse('//', {onComment(){console.log(arguments)}})
[Arguments] {
  '0': 'SingleLine',
  '1': '',
  '2': 0,
  '3': 0,
  '4': { start: { line: 1, column: 0 }, end: { line: 1, column: 0 } }
}
``

`arguments` should be `"SingleLine", "", 0, 2`

**Comment by KFlash** [comment]
@3cp Look at this gist. It's from my private code  https://gist.github.com/KFlash/fa461f7f0cd080e65227eb9a0a683938

If you "adopt" this I guess most of the problems will be solved. Doing `parser.pos - parser.columnPos` after WS has been skipped gives me number`2` as @fisker mentioned.

**Comment by 3cp** [comment]
There was an missing init before loop in my code. Your gist is much bigger change, I will try it for #125.

**Comment by KFlash** [comment]
@3cp I'm still experimenting with my gist. Dealing with comments now

**Comment by KFlash** [comment]
@3cp Study this gist https://gist.github.com/KFlash/688af509a649aa8180d4cb17e7b9de81

Confirmed it's easy to extract comments
