### ISSUE TITLE
Can we add `JSXText.raw`?

### ISSUE THREAD

**Issue by fisker** [meriyah/meriyah#129]
```js
require("meriyah").parse('<div>text</div>',{raw:true,jsx:true}).body[0].expression.children[0]
{ type: 'JSXText', value: 'text' }
```

`babel` has `.extra.raw`, `flow`/`espree` has `.raw`

**Comment by fisker** [comment]
spec has  `raw`

https://github.com/facebook/jsx/blob/master/AST.md#jsx-text

**Comment by fisker** [comment]
I tested other parsers, so we have another problem, the value was wrong

```jsx
<div>&nbsp;</div>
```

Should be `{value: " ", raw: "&nbsp;"}`

**Comment by 3cp** [comment]
We didn't processed the value. I could not find spec on value in facebook/jsx doc. Any inside?

**Comment by 3cp** [comment]
If prettier only need raw, you are probably fine for now after we release the jsx PR.
To proper support value, we would need to add the whole table of html entity names.

**Comment by fisker** [comment]
Yes, it's good enough for prettier.

**Comment by fisker** [comment]
Better open another issue about `JSXText.value`, we could improve later.
