### ISSUE TITLE
`FieldDefinition` -> `ClassProperty`?

### ISSUE THREAD

**Issue by fisker** [meriyah/meriyah#134]
`babel` / `flow` / `@typecript-eslint/parser` uses `ClassProperty`

I believe `FieldDefinition` is a old AST type from `babel`?

```js
 require('meriyah').parse('class A{a=1}',{next:true}).body[0].body.body[0]
{ type: 'FieldDefinition',
  key: { type: 'Identifier', name: 'a' },
  value: { type: 'Literal', value: 1 },
  static: false,
  computed: false,
  decorators: [] }
```

**Comment by 3cp** [comment]
Also PrivateName -> PrivateIdentifier

**Comment by 3cp** [comment]
Latest is called PropertyDefinition, not ClassProperty?

https://github.com/estree/estree/blob/master/experimental/class-features.md

**Comment by 3cp** [comment]
https://github.com/estree/estree/pull/222

**Comment by fisker** [comment]
I didn't know that. I thought estree hasn't support class property.

I'm good with `PropertyDefinition`.

My purpose here is trying to align `meriyah` ast with other parsers, I think other parsers will change their asts, then no rush.

**Comment by 3cp** [comment]
Maybe you can add support of old FieldDefinition for now? I will do a thorough cleanup in future to align with latest estree spec.

**Comment by KFlash** [comment]
@3cp I gave @fisker a "little upgrade" if he checks his email

**Comment by fisker** [comment]
> Maybe you can add support of old FieldDefinition for now? 

Already did.

**Comment by fisker** [comment]
@KFlash Thanks for you invitation, I might don't have time to contribute thought :smile:

**Comment by fisker** [comment]
Another difference between babel and meriyah

babel use `PrivateName.id`, meriyah use `PrivateName.name`.

We are going to follow the new spec anyway, so no need to change for now.

**Comment by 3cp** [comment]
FYI, `PrivateIdentifier.name` is in latest spec. https://github.com/estree/estree/blob/master/experimental/class-features.md#privateidentifier
