### ISSUE TITLE
BigInt should be allowed to use as object key

### ISSUE THREAD

**Issue by fisker** [meriyah/meriyah#136]
```js
require('meriyah').parse('{1n:1n}',{next:true})
Uncaught [ParseError [SyntaxError]: [1:4]: Unexpected token: ':'
] {
  index: 4,
  line: 1,
  column: 4,
  description: "[1:4]: Unexpected token: ':'",
  loc: { line: 1, column: 4 }
}
```

```js
console.log({1n:1})
{ '1': 1 }
```

**Comment by 3cp** [comment]
What's your node/browser version?
```
⋊> ~/g/meriyah on jsx-fix ⨯ node
Welcome to Node.js v12.18.3.
Type ".help" for more information.
> console.log({1n:1})
console.log({1n:1})
             ^^

Uncaught SyntaxError: Unexpected number
```

**Comment by 3cp** [comment]
node v15 works.

**Comment by KFlash** [comment]
It's a valid case. BigInt can be a property key. Also for Class

**Comment by 3cp** [comment]
I see where is missed.
```js
} else if ((parser.token & Token.IsStringOrNumber) === Token.IsStringOrNumber) {
        key = parseLiteral(parser, context);
```

Our Token.IsStringOrNumber only applies to string and number, not bigint.
Should I add bigint to Token.IsStringOrNumber?

ecma spec seems indicating bigint can be used anywhere a normal number fits.
```
NumericLiteral::
  DecimalLiteral
  DecimalBigIntegerLiteral
  NonDecimalIntegerLiteral
  NonDecimalIntegerLiteralBigIntLiteralSuffix
```

**Comment by KFlash** [comment]
Yes. It's easy to update token.ts

**Comment by 3cp** [comment]
also need to update parseLiteral to check bigint.

**Comment by KFlash** [comment]
why? How do you parse BigInt now? Just check for "if (token === Token.BigInt") return parseBigInt)

**Comment by 3cp** [comment]
yes, I am adding the line to parseLiteral, if you add the line outside of parseLiteral, you need to add it in many places after Token.IsStringOrNumber check.
