### ISSUE TITLE
Can't parse `"\8"`

### ISSUE THREAD

**Issue by fisker** [meriyah/meriyah#137]
```js
const a = "\8";
```

This is valid code.

**Comment by KFlash** [comment]
Only in sloppy mode

**Comment by fisker** [comment]
But seems that we don't have an option to parse it.

**Comment by KFlash** [comment]
Look at string literal escape code

**Comment by 3cp** [comment]
Pretty sure ecma allows `\8` and `\9` as NonEscapeCharacter.
Why we reject them? I couldn't find anything about these two in ecma spec.

**Comment by 3cp** [comment]
v3.1.1 is released.
Use `webcompact: true` to support this.
