### ISSUE TITLE
Comment extraction?

### ISSUE THREAD

**Issue by Jaxkr** [meriyah/meriyah#14]
Been looking for a JavaScript parser for a developer tool project I'm working on, and I am so glad I stumbled upon yours, as it it standalone, fast, and compliant.

However, I was curious if there was any support for extracting comments and returning them from a parse. I started digging through the source code and it looks like I could collect comments by adding functionality to `skipSingleLineComment` and `skipMultiLineComment`.

However, before I went changing any code I wanted to inquire as to whether this feature was currently available, and if you would be open to having someone implement it.

**Comment by KFlash** [comment]
Hi. My biggest concern is as always performance regression, but if you want to it's okay you implement this.  I think implementing this as a callback function as in `Acorn` is the right way to go, and it's easiest. You just add a third arg to create. `L48` in `parser.ts`. And more or less copy exactly how I did implement the `source` option. Se  `L214` . 

And the missing functionality for collect comments has to be implemented in `skipSingleLineComment` and `skipMultiLineComment` as you mentioned :)

**Comment by KFlash** [comment]
@Jaxkr If you implement this, you maybe should add a `jsx: true` / `jsx: false` property on the comment output in cases like this `/** @jsx CUSTOM_DOM */<a></a>`. 

See https://github.com/meriyah/meriyah/issues/15

**Comment by KFlash** [comment]
@Jaxkr Is this something you want to add a PR for? I'm kind of stuck with the TS parser madness so have time just now.

**Comment by KFlash** [comment]
@Jaxkr I implemented this now, so I'm closing this issue as it will land in v. 1.4.
