### ISSUE TITLE
Need to process win32 line break correctly

### ISSUE THREAD

**Issue by 3cp** [meriyah/meriyah#146]
I noticed we skipped lots of test files in test262-parser-tests, I tried to unblock them to see what happens.

For example the first skipped file:
https://github.com/meriyah/meriyah/blob/756d990eb3c98487197bade97cb5d34f77a86ea0/test/test262-parser-tests/parser-tests.ts#L9

The 110fa1efdd0868b8.js file contents is
```js
"Hello\
world"
```

But the file is using `win32` line break `\r\n` which causes issue in meriyah.

**Comment by 3cp** [comment]
It seems our code didn't handle LineContinuation inside string literal at all, the successful pass on `\` + `\n` was an accident.

**Comment by KFlash** [comment]
strange. Can you do something like [this](https://github.com/escaya/escaya/blob/master/src/lexer/string.ts#L140)

**Comment by 3cp** [comment]
I did not see you handle LineContinuation in that escaya code either.

**Comment by KFlash** [comment]
A LineContinuation  is `\r`, so what's done is to pass all chars starting with `\` to escaped chars. Then increase the index. If no "switch match" then `return String.fromCharCode(ch);` and you get your empty code point

**Comment by 3cp** [comment]
Thx, so it's not an accident. Just a missing case on `\r\n`.

BTW, it seems test262-parser-tests are being maintained poorly, many unanswered issues.

**Comment by 3cp** [comment]
The LineContinuation supports `\n`, `\r`, `\r\n`, and unicode LS and PS.

http://www.ecma-international.org/ecma-262/11.0/index.html#prod-LineTerminatorSequence

**Comment by KFlash** [comment]
test262-parser-tests is no good. Either try the real test suite or look into https://github.com/v8/v8/blob/master/test/cctest/test-parsing.cc for some edge cases etc

LS and PS are now allowed in string literals, but `\n`, `\r`, and `\r\n` are dissallowed. 

If you read what I wrote in my last comment on how to grab the empty code point, it can be done the same for the sequence `\r\n` if you slice and append the string

`\r`  - res += res + slice...
`\n`  - res += res + slice...

The tricky part is for this cases `\\r` and `\\n`

**Comment by KFlash** [comment]
@3cp I made it just now. https://gist.github.com/KFlash/a8452b70d3596e0f79a2b8d9b3288047

**Comment by KFlash** [comment]
I'm trying to give some "super powers" to the gist I linked too so this can be solved once for all. Give me 30 min.

**Comment by KFlash** [comment]
Done! https://gist.github.com/KFlash/a8452b70d3596e0f79a2b8d9b3288047

Taken from the top of my head, so didn't run any tests against this, but it should work

**Comment by KFlash** [comment]
@3cp  In my gist the cases should be ordered 0, 1, 2 , and you can `index++` - skip the char - before the loop if you update the backslash consumer. I had no time to look into that.

**Comment by KFlash** [comment]
Updated the gist and added escape char scanning. I tweaked it, but you still need to "adjust". I think this should solve this issue

**Comment by 3cp** [comment]
Any reason you write these?
```js
export function scanString(parser: ParserState, cp: number): Token {
  parser.pos++;
  let quote = cp;
```

Instead of keeping existing param name quote?
```js
export function scanString(parser: ParserState, quote: number): Token {
  parser.pos++;
  let cp = quote;
```

**Comment by KFlash** [comment]
No reason. I just tried to avoid assigning of the variable inside the loop. Costs memory.

**Comment by 3cp** [comment]
It turns out a very small bug in existing code, it was sitting there because of missing test coverage.
Let's just patch it for now, worry about the bigger refactoring later.
