### ISSUE TITLE
Support optional private prop?

### ISSUE THREAD

**Issue by fisker** [meriyah/meriyah#148]
```js
class A{a(){obj?.#x.a}}
```

**Comment by 3cp** [comment]
How did you access a private prop from outside of class definition of `obj`?

```
> class B {
... #p = 2;
... foo() { return this.#p; }
... }
undefined
> var b = new B;
undefined
> b.foo()
2
> b.#p
... ;
b.#p
 ^

Uncaught SyntaxError: Private field '#p' must be declared in an enclosing class
> b['#p']
undefined
```

**Comment by fisker** [comment]
```js
class A{
	#x = {a: 1}

	a(){
	return this?.#x.a
	}
}

new A().a()

```

**Comment by fisker** [comment]
```js
class A{
	#x = {a: 1}

	a(){
        const obj = this
        return obj?.#x.a
	}
}

new A().a()
```

**Comment by fisker** [comment]
> How did you access a private prop from outside of class definition of obj?

Not outside, inside.

**Comment by 3cp** [comment]
`obj?.#x` means `obj ? obj.#x : undefined`. So it doesn't make much sense here because `this` is never undefined.

It probably makes sense for `obj.#y?.a`, but again it does not really make sense, because private prop is statically checked by js compiler.

```
> class A{
...   #x = {a: 1}
... 
...   a(){
...         const obj = this
...         return obj.#y.a
...   }
... }
... ;
        return obj.#y.a
                  ^

Uncaught SyntaxError: Private field '#y' must be declared in an enclosing class
```

One possible usage might be
```js
class A {
  #x; // undefined
  a() {
    return this.#x?.a;
  }
}
```

And yes, this code is fine in meriyah.

My argument is because private prop is statically checked, it doesn't make any sense to have `any?.#private` syntax. I will be surprised if ecma allows this. @KFlash any thought?

**Comment by KFlash** [comment]
Just follow what the proposal says

**Comment by fisker** [comment]
You point make sense, I wounder why [Private Fields in `in`](https://github.com/tc39/proposal-private-fields-in-in/blob/master/README.md)? Seems static check fails on superClass privete field too


```js
class A{
	#x = {a: 1}
}
class B extends A{
	a(){
        return this?.#x.a
	}
}

new B().a()
Uncaught SyntaxError: Private field '#x' must be declared in an enclosing class
```

**Comment by fisker** [comment]
This?

```js
class A {
#a=1
a() {return this?.#a}
}

A.prototype.a.call(undefined)
A.prototype.a.call(new A)
```

**Comment by 3cp** [comment]
```
Private class fields and methods

Issue #28: Should optional chains support the upcoming private class fields and private methods, as in a?.#b, a?.#b() or a?.b.#c? Quoting microsoft/TypeScript#30167 (comment):

This one isn't baked into the proposal yet, simply because private fields themselves aren't baked yet. So we don't want to hold up this proposal if that one happens to stall out. Once that one has reached Stage 4, we will address it then.
```

https://github.com/tc39/proposal-optional-chaining/issues/28
https://github.com/tc39/proposal-class-fields/pull/301
https://github.com/tc39/proposal-class-fields/pull/302

**Comment by 3cp** [comment]
In short, there were lots of arguments like ours. But it's in the proposal now.

**Comment by 3cp** [comment]
This works now.
