### ISSUE TITLE
Use Strict Directive needs to be preflighted

### ISSUE THREAD

**Issue by 3cp** [meriyah/meriyah#149]
Found this issue while cleaning up test262 file, not sure if this is possible in meriyah.
It's not a serious bug in real world, as people always put use strict directive at beginning of a scope.

Meriyah rejects following code as per spec:
```
> parse('"use strict"; "\\1";')
Uncaught:
[ParseError [SyntaxError]: [1:16]: Octal escape sequences are not allowed in strict mode
] {
  index: 16,
  line: 1,
  column: 16,
  description: '[1:16]: Octal escape sequences are not allowed in strict mode',
  loc: { line: 1, column: 16 }
}
```

But failed to do so if the use strict directive is after the problematic code.
```
> parse('"\\1"; "use strict";')
{
  type: 'Program',
  sourceType: 'script',
  body: [
    { type: 'ExpressionStatement', expression: [Object] },
    { type: 'ExpressionStatement', expression: [Object] }
  ]
}
```

**Comment by KFlash** [comment]
Should be an easy fix? What about using the mutual parser flag for this if in function body, and if on top level use a variable outside the loop.

**Comment by 3cp** [comment]
I didn't follow. When passing `"\1"`, how did you turn on strict mode from the token (`"use strict"`) not parsed yet?

**Comment by KFlash** [comment]
Give me 30 min to come up with a solution

**Comment by KFlash** [comment]
It's an octal so you simply add a mutual parser flag in the number scanner and other places where octals occur. **Note** You need to reset that flag for each time you do the token dispatch. Soon as you have the mutual parser flag, try something like this

```ts
 let seenOctal = false;

  while (parser.token === Token.StringLiteral) {
    expr = parseLiteral(parser, context);
    // "use strict" must be the exact literal without escape sequences or line continuation.
    if ( VALID STRICT MODE CODE  {
      if (seenOctal === 1) // TODO! Throw an error
      context |= Context.Strict;
    } else {
      if (seenOctal  === 0 && (parser.flags & Flags.Octals) === Flags.Octals) {
        seenOctal  = 1; // We seen it, but no strict mode yet
      }
    }

    statements.push(parseDirectiveExpression(parser, context, index, start, line, column, expr));
  }

```

**Comment by 3cp** [comment]
It's not just octal, there are many other failures in strict mode need to be handled. Browser might re-parse the whole function scope when strict mode is changed at middle of the function scope.

**Comment by 3cp** [comment]
I don't understand why ecma did not enforce directive to be only allowed at top of a function scope.

**Comment by KFlash** [comment]
Open an ticket in the ECMA specs repo

**Comment by 3cp** [comment]
Just noticed [tenko](https://github.com/pvdz/tenko) did very well for this case.

And I found out bit more in nodejs
```
>  "\1";"use strict";
 "\1";"use strict";
   

Uncaught SyntaxError: Octal escape sequences are not allowed in strict mode.
>  "\1";1+1;"use strict";
'use strict'
```

You see, when `"\1"` and `"use strict"` are not adjacent, **js parser did not complain**. And tenko replicated this behavour 100%!

There must be something explicit in ecma spec...

BTW for reference, leading "use strict" is always in effect as we expected.
```
> "use strict"; 1+1; "\1";
"use strict"; 1+1; "\1";
                     

Uncaught SyntaxError: Octal escape sequences are not allowed in strict mode.
```

**Comment by KFlash** [comment]
What about copy Tenko on that part? Not sure about the regex but..

**Comment by 3cp** [comment]
I will try to decipher ecma spec first. That adjacency is weird.

**Comment by KFlash** [comment]
In my own language (*I invented a language similar to TS, but faster*), I'm skipping WS first, and then I do the directive scanning with tons of bitmasks. That way I can add a diagnostic (throw an error) with bitmasks fiddling, and the issue you mentioned before is non-existing. I'm not even using the scanner code. 

This because the entire code is structured as an optimized finite state machine. There is no concern of nested productions because I'm only validating strings (not even parsing them), aborting with everything else. And the validation will not happen unless a single or double quote are seen (start of string literal).

After I reset to "normal state" and do the normal parsing.

**Comment by 3cp** [comment]
```
> "\1";"use strict"
"\1";"use strict"
  

Uncaught SyntaxError: Octal escape sequences are not allowed in strict mode.
> var a = "\1";"use strict"
'use strict'

> var a = "\1";"use strict";"\1"
'\u0001'
```

The first case is due to `"\1"` is a directive. The two expression statements formed "A Directive Prologue" at beginning of list statements.

In the second case, `"use strict"` doest **NOT* form "A Directive Prologue" because it's not from the beginning of the list statements.

The third case confirmed `"use strict"` has no effect if it's not in "A Directive Prologue".

In short, `"use strict" can appear in any location of the whole "A Directive Prologue", it can affect directives (string literal expression) before it.

ECMA did enforce the location of directives.

**Comment by KFlash** [comment]
so, easy fix?

**Comment by 3cp** [comment]
I am not going to try, at least for now.
This bug has no impact on real world code. It's just an edge case in the spec. People has no reason to write code like this, rather than testing a parser's spec compliance.

**Comment by 3cp** [comment]
For record, the disabled test262 tests.
https://github.com/meriyah/meriyah/blob/a903f27808d9f65743f565f6e8e0967dc62d35fe/test/test262-parser-tests/parser-tests.ts#L22-L25

**Comment by 3cp** [comment]
Just found out meriyah does the preflight correctly in function body.
```
> parseScript('(function (package) { "use strict"})')
Uncaught SyntaxError: [1:35]: Unexpected strict mode reserved word
```

Need to apply the same thing to top statement list.

**Comment by Tcjmd** [comment]
@3cp I like this challenge :)  I will try study the code and find a solution.

I can only guide you how to solve. I can't use computer yet

What about this KFlash? He said easy fix

**Comment by 3cp** [comment]
Also need to fix `function a() { "\1"; "use strict"; }`.

KFlash has long been retired from coding happily :-)

**Comment by Tcjmd** [comment]
See my reply in the other issue.

For your last example I think code exist already?

Should be done in funcbody parsing. Easy I guess. Use local var `3cp` set to false. If found number like that inside the while loop, set to true.

Do the validation check. You can see where to do the validation

**Comment by Tcjmd** [comment]
I try help you out here. Can you help to push meriyha buildflow to the repo I invited you to? Empty src and test folder.
I will see what I can do from a CP

**Comment by 3cp** [comment]
meriyah buildflow is not clean, many manual scripts. You probably want a clearer setup.

For my own project nowadays, I prefer bun's native bundler and tester, way faster than other setup.

Just follow the doc
https://bun.sh/docs

**Comment by Tcjmd** [comment]
I can't do anything of that from a CP :) I only need a simple workflow that build and rip off TS types and do testing. No need for Prettier or other dependencies. Rollup bundle quit nice.
A must to have a sub dir where to put c / assembly files so I build script can  be expanded to compile them.

Anyway. Did my tips help you to solve the issues? I have lots of time so if you have other issues, I can look into them if you want

**Comment by 3cp** [comment]
Thx, I have not started studying the issue, nor checking through yours. Got day job.

Sorry, no time to help your setup either :( Anyway, pretty sure you have no trouble to get a simple rollup config up and running.
