### ISSUE TITLE
Implement snapshot without any 3rd party NPM packages

### ISSUE THREAD

**Issue by KFlash** [meriyah/meriyah#151]
Use of snapshots will make it much easier to test the parser and handle over the 60k different tests

**Comment by 3cp** [comment]
BTW, tenko has very nice document style tests.

**Comment by KFlash** [comment]
Can you "borrow" that one ?

**Comment by 3cp** [comment]
Maybe.
I think a generic test262-estree should be good for us, and any estree parsers. It can keep up with latest ecma262, and latest estree specs. Sounds like lot of effort too.

**Comment by jaydenseric** [comment]
May I suggest [`snapshot-assertion`](https://github.com/jaydenseric/snapshot-assertion); it has zero dependencies, tiny source, and is as un-opinionated as a standalone snapshot assertion function can get. It's fully tested with 100% code coverage. I rely on it to test my own packages.

One of the nice things about it is that you can save the snapshot files with whatever file name extensions make sense for the content of the snapshot, which allows you to open JSON, markdown, HTML, etc. snapshot files in your editor and get syntax highlighting. Here is an example of snapshotting an AST as JSON:

https://github.com/jaydenseric/jsdoc-md/blob/50d9cb43f17a6afa51340ff8f83e889293c71dbe/test/private/typeJsdocAstToMdAst.test.js#L72-L78

I frequently use it to snapshot test CLI stdout:

https://github.com/jaydenseric/find-unused-exports/blob/2a7ba69cab2e4a4f93a11733efa7de887b222449/test/cli/find-unused-exports.test.js#L25-L31

**Comment by KFlash** [comment]
@jaydenseric Do you want to put up a basic PR for this with a few running tests so we could use it as a base and port all tests?

**Comment by jaydenseric** [comment]
@KFlash is there a particular test that stands out for me to start with?

**Comment by KFlash** [comment]
@jaydenseric Just make a random test. For example "let a = {}; (x);" or choose from test folder

**Comment by KFlash** [comment]
@3cp Closing. Seems to be no progress on this issue ticket, and it's hard in general to implement this.
