### ISSUE TITLE
Missing `dist/meriyah.d.ts` file

### ISSUE THREAD

**Issue by fisker** [meriyah/meriyah#153]
This file is not generated.

**Comment by fisker** [comment]
Ah, found it, it's in `dist/src/meriyah.d.ts`, so fix this in package.json ?

https://github.com/meriyah/meriyah/blob/master/package.json#L9-L10

**Comment by 3cp** [comment]
Not sure if this is a regression due to tsc? Let me check old versions.

**Comment by 3cp** [comment]
Looks like a regression.

**Comment by 3cp** [comment]
Oh, it's my code. Caused by `export { version } from '../package.json';`

**Comment by 3cp** [comment]
This is troublesome for typescript. Do you have any idea how to bypass this issue?

**Comment by fisker** [comment]
Another thing, this is CommentType  not right https://github.com/meriyah/meriyah/blob/cf8417b97a6f0ae9e66639bede5c2c689dadbc22/src/estree.ts#L35

**Comment by 3cp** [comment]
what's wrong there?

**Comment by fisker** [comment]
```diff
- export type CommentType = 'Line' | 'Block' | 'HTMLOpen' | 'HTMLClose'; 
+ export type CommentType = 'MultiLine' | 'SingleLine' | 'HashbangComment' | 'HTMLOpen' | 'HTMLClose'; 
```

**Comment by 3cp** [comment]
Right, I am not sure why there is another definition in src/lexer/comments. Should find someway to reuse.

**Comment by fisker** [comment]
Change `estree.ts` and `import {CommentType}` in src/lexer/comments?

**Comment by 3cp** [comment]
@KFlash there is mismatch of type

https://github.com/meriyah/meriyah/blob/cf8417b97a6f0ae9e66639bede5c2c689dadbc22/src/estree.ts#L35

https://github.com/meriyah/meriyah/blob/eeb0c067c94244b7710cd0f78e2579074e5f6f74/src/lexer/comments.ts#L14

Any idea how to define once and reuse in both places?

**Comment by 3cp** [comment]
@fisker that CommentType enum in src/lexer/comments is not backed by integer, not string.

**Comment by 3cp** [comment]
v3.1.4 is released with updated type path in package.json.

**Comment by fisker** [comment]
We'll be able to use `meriyah` in prettier to format `.js` in next few days, but we don't use JavaScript...:smile:

**Comment by KFlash** [comment]
@3cp Just change the names in estree.ts ?

**Comment by 3cp** [comment]
Sure. Will do.

**Comment by 3cp** [comment]
Patched in master branch.
