### ISSUE TITLE
`package.json` path in `dist/src/meriyah.d.ts` not right

### ISSUE THREAD

**Issue by fisker** [meriyah/meriyah#155]
Line 7 [`meriyah/dist/src/meriyah.d.ts`](https://unpkg.com/browse/meriyah@3.1.5/dist/src/meriyah.d.ts), it should be `../../package.json`

**Comment by 3cp** [comment]
It's auto generated by tsc.
It refers to `dist/package.json` (which is also auto generated by tsc as part of the typing), not the root `package.json`.

**Comment by 3cp** [comment]
I see what went wrong.

The `dist/package.json` is only generated by `npm run build`. The `npm run bundle` did not generate that file. Investigating.

**Comment by 3cp** [comment]
v3.1.6 is released.
