### ISSUE TITLE
track parent nodes

### ISSUE THREAD

**Issue by KFlash** [meriyah/meriyah#159]
@3cp Meriyah should track parent node and add it as an last option to the comment extraction code. It will help Prettier to figure out where to attach their comments.

`import /* 1 */ { /* 2 */ x /* 3 */ } /* 4 */ from 'a';`

`async /* a */ function /* a */a() {}`

Try pretty print them with Prettier and you get the point.

@fisker Would that help Prettier?

**Comment by fisker** [comment]
You mean add parent to Node or Comment?

**Comment by KFlash** [comment]
yes. Parent node as func arg same as comment type, loc tracking etc

**Comment by fisker** [comment]
We  have many Javascript parsers, maybe not  very useful to have this for just one parser, we  need keep these parsers behave the same.

**Comment by KFlash** [comment]
You are right. I'm closing this, but then how to solve all comment issues in Prettier?
