### ISSUE TITLE
Messed up location in TemplateLiteral

### ISSUE THREAD

**Issue by jods4** [meriyah/meriyah#167]
Open this in AST explorer: 
https://astexplorer.net/#/gist/5456736625f73c2da2f35c1d2d7deca5/679cef422dad9ffff19e0894129d3f58ecb98740

The code is simply:
```js
function f() {
  return `123456789${10}1234567890${20}`;
}
```

Now observe the `loc` of the `TemplateLiteral` and its `quasis` (the `expressions` seem ok).
`TemplateLiteral.loc` seem to start at the first expression hole.
Quasis `loc` end before they start, or are zero-length.

**Comment by fisker** [comment]
I thought this was fixed? https://github.com/meriyah/meriyah/commit/ff71744d5b20b87c3bfbba6534656d3768215207

I'm on cellphone, can't confirm.

**Comment by jods4** [comment]
You're right AST explorer is pretty old, which is quite inconvenient for testing and debugging :(

Based on the initial observations in my real program, it looked like the start of the `TemplateLiteral` seems to be at the first `expression` hole even in 4.0.0.

If you think this isn't the case I can debug further with my real program, I didn't notice AST Explorer was so old.

**Comment by 3cp** [comment]
Yes, pls verify with latest meriyah locally.

**Comment by jods4** [comment]
@3cp You can put the same code in there: https://meriyah.github.io/meriyah/
And the Literal also supposedly starts at column 21, which matches the problems I observe on my machine :(

I also observed that if you remove the `return`, for some weird reason the starting column position is correct.

**Comment by KFlash** [comment]
@jods This is JSX not template

**Comment by jods4** [comment]
@KFlash I don't understand? I unchecked JSX and checked module in the left sidebar.

**Comment by KFlash** [comment]
I did a comparison here. start & end values is off by 1 a few places,. I guess the whitespace screw this up.

Template tail start at 54 and end at 54. If you consume a backtick the end value should increase with +1. So the value should be 54 - 55.

Not sure about column values

**Comment by jods4** [comment]
Here's an illustration of the problem:
![image](https://user-images.githubusercontent.com/3832820/105688718-37723a80-5efa-11eb-99ac-b3ae91a60f8d.png)
