### ISSUE TITLE
ES Next: Logical assignment operators

### ISSUE THREAD

**Issue by jods4** [meriyah/meriyah#168]
This proposal is completed (stage 4) and supported by TS, it's expected to be part of ES2021.
https://github.com/tc39/proposal-logical-assignment

It also works in most browsers today:
https://caniuse.com/mdn-javascript_operators_logical_nullish_assignment

Can you add support for it?
I have code that uses `??=` and it doesn't parse :(

**Comment by KFlash** [comment]
Try use option `next` for now.

cc / @3cp

**Comment by jods4** [comment]
I use `next: true` in my options.
Many things work, like `import.meta` but `??=` doesn't and I don't see it listed on the README.

Is it supposed to work? I can investigate further if it is, but I have the impression it's not.

**Comment by KFlash** [comment]
What is the code line you try to parse? It's implemented in Meriyah without any need to enable `next`.

You can see it [here](https://github.com/meriyah/meriyah/blob/master/src/parser.ts#L3377-L3384)

**Comment by jods4** [comment]
@KFlash I saw you have a parser of your own. Would you advise using it?
I value ES support, speed and require a standard AST with locations.

**Comment by KFlash** [comment]
I think Meriyah is the best choice.  I have my own parser yes, but it's part of my non-open source project.
It goal was to do the same as Babel with transformers, linting, minifier, prettify, parse TS etc. 

I archived my goal and still playing around.  

You can check out [this readme](https://github.com/kataw/kataw) and try out the demo.

Meriyah is a simple JS parser that follows ESTree and also used in Prettier. It's an better alternative than for example Acorn due to it's performance.

**Comment by 3cp** [comment]
Looks like not difficult to implement. Question @KFlash, do we want to shift the numbers below assign operators to make spaces for `||=` `&&=` and `??=`? Or we can give new numbers for them 

```js

  /* Assign operators */
  Assign                  = 29 | IsAssignOp | IsClassField, // =
  ShiftLeftAssign         = 30 | IsAssignOp, // <<=
  ShiftRightAssign        = 31 | IsAssignOp, // >>=
  LogicalShiftRightAssign = 32 | IsAssignOp, // >>>=
  ExponentiateAssign      = 33 | IsAssignOp, // **=
  AddAssign               = 34 | IsAssignOp, // +=
  SubtractAssign          = 35 | IsAssignOp, // -=
  MultiplyAssign          = 36 | IsAssignOp, // *=
  DivideAssign            = 37 | IsAssignOp | IsExpressionStart, // /=
  ModuloAssign            = 38 | IsAssignOp, // %=
  BitwiseXorAssign        = 39 | IsAssignOp, // ^=
  BitwiseOrAssign         = 40 | IsAssignOp, // |=
  BitwiseAndAssign        = 41 | IsAssignOp, // &=
  
  // Do we give 42, 43, 44 to ||=, &&=, and ??= ?
  // Or use 136, 137, 138 (after the last one JSXText 135)?

  /* Unary/binary operators */
  TypeofKeyword      = 42 | IsUnaryOp | Reserved,
  DeleteKeyword      = 43 | IsUnaryOp | Reserved,
  VoidKeyword        = 44 | IsUnaryOp | Reserved,
  Negate             = 45 | IsUnaryOp, // !
  ```

**Comment by KFlash** [comment]
The order doesn't matter, but probably easier to understand if grouped together like `41`, `42` ... etc

Do not forget to add `| IsAssignOp` behind the numbers or else this will not parse :P

The token dispatch code also need a quick update for this to work, but nothing of this is super hard. Maybe 10 min to fix it.

**Comment by 3cp** [comment]
@KFlash does stage4 mean still need `next` flag?

**Comment by KFlash** [comment]
It's means it's implemented into all browsers and part of the ECMA language, so no!

**Comment by 3cp** [comment]
Good, I didn't do that.
