### ISSUE TITLE
Invalid location start line

### ISSUE THREAD

**Issue by jods4** [meriyah/meriyah#169]
Repro:
https://astexplorer.net/#/gist/5e24a339b0b8ce07f801c77409c48cf7/8ddd8d42d1e2dd3b73626f63df71702ab14fefe1

Sample code:
```js
function _sfc_render() {
    return _createBlock("div", {
    style: { backgroundImage: 'url(' + _ctx.playerImg + ')' }
  })
}
```

Bug:
If you look at the `loc.start.line` of the innermost `BinaryExpression` (ie `'url(' + _ctx.playerImg`), you'll notice it's equal to 88, which can't be right in a 5 lines snippet.

88 is also (and correctly) its start position, so I guess it's just a typo between two local variables.

Those location bugs are critical because I'm trying to use this parser with `recast`, which relies heavily on `loc`. Incorrect locations like this snippet makes it crash.

**Comment by KFlash** [comment]
recast? What are you trying to do? Comments?

cc / @3cp

**Comment by jods4** [comment]
@KFlash Recast is the cool lib behind codemods, also Facebook jscodeshift
https://github.com/benjamn/recast

I'm writing some code transforms with it and I choose meriyah for the parser... for now!
Recast requires a "standard" AST and in this context I value speed and ES support, so it seems meriyah is a perfect fit.
Just bummed by those location problems when testing on large real-world codebase.

**Comment by KFlash** [comment]
I had a look at recast. I can actually do most of the same with my own parser (toolbox) that I mentioned in your other issue ;)
