### ISSUE TITLE
ParseError: Illegal return statement

### ISSUE THREAD

**Issue by mamaniv** [meriyah/meriyah#18]
I get ParseError: Illegal return statement for code that includes return statement on the module body, outside function call.

Minimum code to reproduce:
`const meriyah = require('meriyah');`
`const tree = meriyah.parse('return;'), {
        ranges: true
      });
`

I know that this usage is not a best practice, but it works and it is supported by other parsing modules like Esprima.

**Comment by nchanged** [comment]
@mamaniv I believe `globalReturn: true` is the option you need.

**Comment by mamaniv** [comment]
@nchanged Thank you, it works now!
