### ISSUE TITLE
Question: How to traverse AST

### ISSUE THREAD

**Issue by fisker** [meriyah/meriyah#180]
Is there a `traverse` function or `visitorKeys` so I can use `estraverse` to traverse AST.

**Comment by 3cp** [comment]
estraverse works with any estree AST tree.
```
estraverse.traverse(ast, ...
```

**Comment by fisker** [comment]
I know, but I think meriyah better provide `visitorKeys`.

**Comment by fisker** [comment]
For example, we have `PropertyDefinition`, but [estraverse don't have keys](https://github.com/estools/estraverse/blob/master/estraverse.js#L151) for it.

**Comment by 3cp** [comment]
Guess that's for estraverse to keep up to date with estree?

**Comment by fisker** [comment]
I'm not sure, but `babel` have `@babel/traverse`, `espree`  and `@typescript-eslint/typescript-estree` have `.VistorKeys` exported.

Here is how babel do https://github.com/babel/babel/blob/e735266dee02144f168a5547fe14f3fd0c553ee4/eslint/babel-eslint-parser/src/visitor-keys.js

I can understand if you decide wontfix.

**Comment by 3cp** [comment]
I am confused. Is VisitKeys something estraverse can consume at runtime?

**Comment by fisker** [comment]
> By passing visitor.keys mapping, we can extend estraverse traversing functionality.

https://github.com/estools/estraverse#example-usage

**Comment by fisker** [comment]
By default, unknown knows will fallback to `Object.keys` example, if node has `.comments`, it will traverse over comments.

But if `keys: {PropertyDefinition: ['key', 'value']}`, estraverse  will only look `key` and `value`.

**Comment by 3cp** [comment]
Sounds like easy improvement. Why don't you send PR :-)

**Comment by fisker** [comment]
I'm not sure if I can do this, as I don't use TS.

**Comment by 3cp** [comment]
It's probably easier (plus better user experience) to contribute to estraverse with the missing node types.

**Comment by fisker** [comment]
Thanks for the advice.
