### ISSUE TITLE
Is it possible to allow "@" to be at the start of a function declaration?

### ISSUE THREAD

**Issue by LumenUI** [meriyah/meriyah#181]
Hello! I'm working on a project named as "Native JavaScript", a highly-optimizing compiler for JavaScript (with static typing). I've come to sway towards the idea of macros, little code snippets you can easily add to your project in a few lines instead of having to type them manually. I've decided on all macros starting with an "@" symbol. Is it possible to allow Meriyah to accept functions that start with the illegal "@" symbol?

**Comment by 3cp** [comment]
I am afraid not. That's not part of ECMA spec or any extension/proposal.

In fact, the decorator proposal (which meriyah currently supports) uses `@` for a different meaning. It will land in EMCA spec in future (no idea how long will it take).

**Comment by KFlash** [comment]
@3cp Could tweak it so `@!` could be allowed - in line with hashbang

@LumenUI Highly optimized? Perf is Meriyah perf?

**Comment by 3cp** [comment]
Right now, the parser sees `@` as the starting point of a list of decorators. Allowing `@` to be starting point of either decorator or function could touch lots of code, not just the function parsing.

Are you proposing `@!macro` instead of `@macro`? It looks bit funny :-)
Maybe a better choice is `%macro` or `#macro`? (`#` maybe troublesome too as it's used for private class variable). `%` might be cheap as long as it's the start of a statement.
But anyway, this is some kind of extension (such as jsx).

**Comment by KFlash** [comment]
`%macro` sounds like a good option :)

**Comment by lazarljubenovic** [comment]
Prior art: percentage sign in front of function calls is used by Node when using the `--allow-natives-syntax` flag.

**Comment by LumenUI** [comment]
Thank you everyone! Maybe I'

> @3cp Could tweak it so `@!` could be allowed - in line with hashbang
> 
> @LumenUI Highly optimized? Perf is Meriyah perf?

Meriyah is probably the fastest parser I've seen. It's very well and extensively featured, but they're really only things you'd want to use given a bigger project. It's been a life-saver with all of these options (especially since it's really really fast compared to other highly-featured parsers. In my experience, Acorn & Esprima are slower than this parser.). Meriyah seems to be very well optimized. 

On the topic of the "@" starting a function, I've come up with a fix. I didn't want to start macros with "_" for example, I was looking for something not implemented in the ECMA specification so that it didn't break any already existing code. I'll see what I can do with the way Meriyah deals with functions and think of a good character to start functions with.  Anyhow, if I find a solution, I'll reopen this issue or message you guys here. Feel free to close the issue.

_**Thank you everyone for the activity and immediate response!**_

**Comment by LumenUI** [comment]
Hello again! I've come up with a solution to my problem. Macros will be declared with the "$_" starting primer. It will first search for a function declared under that name and shoot a warning if a macro under that name is found as well. If the function isn't declared, then we search for the macro and operate like a macro would.

**Comment by KFlash** [comment]
@LumenUI What's the project you are working on?
