### ISSUE TITLE
Meriyah does not properly follow ECMA standards on function declaration and calling.

### ISSUE THREAD

**Issue by LumenUI** [meriyah/meriyah#182]
When experimenting with Meriyah, I discovered the parser properly registers the following invalid function declarations and calls:

```
function 10() {
   return 10;
}

10();
```

```
function "string"() {
   return "string"();
}

"string"();
```

Meriyah also struggles when calling functions. It will assume that the name of the function being called is an identifier, and not a literal.

**Comment by 3cp** [comment]
Probably missed check in
https://github.com/meriyah/meriyah/blob/3c0b15607b96cd2a7906f043c9cff8ea940116d5/src/common.ts#L391

**Comment by 3cp** [comment]
@KFlash what's this line doing?

https://github.com/meriyah/meriyah/blob/3c0b15607b96cd2a7906f043c9cff8ea940116d5/src/parser.ts#L4800

It says `(context & (Context.Strict | Context.Module)) << 11`, the shifting 11 bits to the left moved the `strict` and `module` context to `InYieldContext` and `InAwaitContext`. I have no idea why it does that.

**Comment by KFlash** [comment]
validates func names and remove module and strict check

**Comment by 3cp** [comment]
Why shift 11 bits?

**Comment by 3cp** [comment]
I think I missed the leading `context | ...` but I still don't understand the logic.

**Comment by KFlash** [comment]
then rewrite it. I guess that logic broke at some point where token.ts was updated with support for newer AST nodes

**Comment by 3cp** [comment]
That logic was not the reason of this bug. I am just curious about the line which I still don't understand.

**Comment by KFlash** [comment]
The logic is - I think - is that await and yield has a value around 21?  Then you shift to left so you can unset this masks. Doing so will let you validate cases that should be valid even in async or yield context

**Comment by 3cp** [comment]
There are lots of missed rejection on CallExpression, for example:
```js
["a"]();
var a = {a:1}();
null();
true();
false();
```

It's bit hard to clear up all of them, which leads me to think maybe our `Flags.DisallowCall` is not well fitted for its purpose.

I fixed all the above, but surely there are more (mainly in parsePrimaryExpression).

**Comment by 3cp** [comment]
@KFlash some interesting finding. In real JS parser (nodejs), `null(), true(), false()` are not parser error, but runtime error.
```js
function a() { null(); }
a(); // error throws on this line, not previous line
```

I guess we don't need to reject the 3 in parsing.

**Comment by 3cp** [comment]
My lord `"a"()` is runtime error too.
```js
function a() { "a"() }
```

This parses with no issue in browser or nodejs.

@KFlash I guess we don't change the rejections of CallExpression at all?

**Comment by 3cp** [comment]
`1()` is runtime error too.

**Comment by 3cp** [comment]
Other parsers like acorn and TS do not reject them.

**Comment by LumenUI** [comment]
Apologies.

**Comment by 3cp** [comment]
@LumenUI nothing to be sorry for. It was a valid point, and very subtle and surprising behavior, which clarified some edge cases.

In fact, meriyah's behavior is still not same as native JS parser. `[]()` and `({}())` are parsing time error (means even when wrapped inside function) but meriyah did not pick them up. I will open another issue to clean up that.

**Comment by 3cp** [comment]
NVM, my mistake, `[]()` and `({}()` is runtime error too :-)
