### ISSUE TITLE
JSX with comments not correctly parsed

### ISSUE THREAD

**Issue by fisker** [meriyah/meriyah#185]
Examples:

```jsx
<a><// line
/a>;
```

```jsx
<a></* block */
/a>;
```

```jsx
</* open fragment */>
</ /* close fragment */>;
```

**Comment by 3cp** [comment]
meriyah also did wrong on white spaces, it rejects following:
```html
<a><  /a>
```

**Comment by 3cp** [comment]
Cannot get my head around the cooperation between the normal js scanner and the jsx scanner.
Probably park this one for a while. Need more time to study the code base.
