### ISSUE TITLE
Error trying to use top-level await?

### ISSUE THREAD

**Issue by FredKSchott** [meriyah/meriyah#186]
```
>  require('meriyah').parseModule('const foo = (await bar)', {next: true})
Uncaught: [ParseError [SyntaxError]: [1:18]: 'Await' may not be used as an identifier in this context] {
  index: 18,
  line: 1,
  column: 18,
  description: "[1:18]: 'Await' may not be used as an identifier in this context",
  loc: { line: 1, column: 18 }
}
```

I found https://github.com/meriyah/meriyah/issues/29 but it looks like that issue may have been closed without implementation. 

Top-level await is now stage 3, and supported in Node.js v14+.

**Comment by 3cp** [comment]
@KFlash to support this, is it just removing `Context.InAwaitContext` from the code base?

**Comment by 3cp** [comment]
NVM, it seems more complex that that.

**Comment by KFlash** [comment]
hmm long time since I was focused on that kind of simple code :)

You can't just remove that context, then tons of async tests will fail.

Validate if you come directly from TopLevel when parsing out await is one option. If not in a func body, but on top level, parse it out. Follow the specs.

But Meriyah is all about no-lookahead, so what if you do it simple and just add a 'await' keyword in 'StatementListItem'. It will only be invoked if on TopLevel. And deal with it from there?

**Comment by 3cp** [comment]
I will study the spec when I got more time.

**Comment by 3cp** [comment]
https://tc39.es/proposal-top-level-await/#sec-modules

Adding it to StatementListItem seems not enough, there is also top-level AwaitExpression and few others.

```js
export const output = process((await dynamic).default, await data);
```

**Comment by KFlash** [comment]
PrimaryExpression?

**Comment by 3cp** [comment]
I don't understand that spec notation well enough to understand what's changed in the above proposed spec change.

**Comment by KFlash** [comment]
then open an issue and mark it as "Good first issue" 👍

**Comment by KFlash** [comment]
Any plans to implement this?

**Comment by 3cp** [comment]
No. I have not spent any time on this.

**Comment by aladdin-add** [comment]
TLA has been stage-4 now. refs: https://github.com/tc39/proposals/commit/99fa42a0863b1915eccead5bd2939ed5f468caab

**Comment by KFlash** [comment]
@aladdin-add Stage 4? So it needs to be implemented in Kataw too?

**Comment by aladdin-add** [comment]
yes!

**Comment by aladdin-add** [comment]
and class fields. refs: https://github.com/tc39/ecma262/pull/1668

**Comment by FredKSchott** [comment]
Any eta on when this may get looked ? It's completely fine if the answer is "not for a while", we're just looking for a fix in Snowpack and may move back to acorn (at least for now) if that's the case  https://github.com/snowpackjs/snowpack/pull/2987

**Comment by 3cp** [comment]
At least I am not working on this, not much spare time. @KFlash ?

**Comment by KFlash** [comment]
Everyone can do a PR. I'm busy with Kataw.

@FredKSchott  Acorn's implementation has some flaws / bugs. They recently fixed one bug.

**Comment by KFlash** [comment]
It's super easy to get this implemented. Swap [this line](https://github.com/meriyah/meriyah/blob/master/src/parser.ts#L3596) with this code `if (context & (Context.Module | Context.InAwaitContext)) {` and it's implemented.

Need ofc. fix the non failing. See Kataw on how I solved that

**Comment by 3cp** [comment]
v4.2.0 is released with this feature.
