### ISSUE TITLE
Should throw on `async () => await 5 ** 6;`

### ISSUE THREAD

**Issue by fisker** [meriyah/meriyah#187]
Babel PR https://github.com/babel/babel/pull/12441

**Comment by 3cp** [comment]
I am not very clear about the issue.
Does this come from an ambiguous spec on the precedence of "await" and "**"?

**Comment by 3cp** [comment]
https://github.com/tc39/ecma262/issues/2197
https://github.com/tc39/notes/blob/master/meetings/2020-11/nov-16.md#handling-await-in-left-operands-of-exponentiation

I am little surprised to see the discussion is all about the spec on left operands of exponentiation. Nobody talked about the precedence of operators??

**Comment by fisker** [comment]
Yes, I think so, check [this](https://github.com/tc39/ecma262/issues/2197)

**Comment by 3cp** [comment]
I could not find precedence discussed there.

**Comment by 3cp** [comment]
Now I understand bit more, Estree defined ecma ExponentiationExpression inside BinaryExpression.
But ExponentiationExpression requires left operand to be UpdateExpression, while BinaryExpression does not do special check when operator is `**` (highest precedence).

**Comment by 3cp** [comment]
I need to check more. Our code seems rejecting other Non-UpdateExpreesion just fine `+2**2`, `delete 2**2`.
