### ISSUE TITLE
"Speed Comparison" page does not work on Chome 90.

### ISSUE THREAD

**Issue by y-ich** [meriyah/meriyah#189]
Hi.

I knew meriyah just now and tried "[Speed Comparison adapted from Esprima's Speed Comparison](https://meriyah.github.io/meriyah/performance/)"  but it does not work on Chrome 90 for macOS.

Here is an error message on console.

    Uncaught TypeError: Cannot read property 'version' of undefined
        at Object.version (compare.js:42)
        at reset (compare.js:286)
        at runBenchmarks (compare.js:379)
        at HTMLInputElement.id.onclick (compare.js:387)

**Comment by aladdin-add** [comment]
thx for the report, seems the pages was not updated. I'll make a temp fix later.

**Comment by y-ich** [comment]
I confirmed that it worked well.
