### ISSUE TITLE
make the error messages more informativ

### ISSUE THREAD

**Issue by KFlash** [meriyah/meriyah#192]
should refactor the error messages to be more informative. "unexpected token" doesn't tell me much. Also some error messages is out of scope.

Make it more dynamic and context bases.

Play with Kataw and you get the point:  https://kataw.github.io/kataw/kataw_ast/

**Comment by KFlash** [comment]
@3cp  Take a look at this error diagnostics 

https://github.com/kataw/kataw/blob/83b25a20ea8a6ffb8cf419b2cb5c1678e4e96f7e/test/__snapshot__/parser/expressions/classes/invalid-class-fields.md#diagnostics

**Comment by 3cp** [comment]
Did you remove escaya in favor of kataw?

**Comment by KFlash** [comment]
Not me. My student did that. Why?
