### ISSUE TITLE
context masks turns into negative value

### ISSUE THREAD

**Issue by KFlash** [meriyah/meriyah#193]
`OptionsUniqueKeyInPattern = 1 << 31,`  is a negative value and can cause conflicts and unexpected things can happen :)

**Comment by 3cp** [comment]
As long as we only do bitwise operations around those options, it could be fine?

**Comment by 3cp** [comment]
https://github.com/meriyah/meriyah/search?q=OptionsUniqueKeyInPattern

Looks fine to me.

**Comment by KFlash** [comment]
It looks okay, but I guess it's value is something like '-242585759" ? I didn't check it, but in some cases NodeJS / browser can end up mixing together multiple context masks when this is the only one you want to use. So suddenly you are in strict mode and disallow in context while parsing in module goal etc.

**Comment by prantlf** [comment]
I hope that you're right that the current code is fine. Shouldn't the following check use `=== 0` to be able to sleep well? I suspect that as soon as somebody sets `options.uniqueKeyInPattern` the condition will accidentally return true...

```js
if ((context & Context.SuperCall) < 1) report(parser, Errors.SuperNoConstructor);
```

**Comment by 3cp** [comment]
It's possible to use bigint to store the option bits, it supports all bitwise operations.
The question is whether we want to take the performance hit (but I have not found any existing benchmark for bigint bitwise operations).
