### ISSUE TITLE
performance regression

### ISSUE THREAD

**Issue by KFlash** [meriyah/meriyah#195]
Meriyah is a simple ESTree parser and doesn't do much "under the hood". I ran a perf comparison against Kataw - a CST parser that does much more than meriyah - and found perf  regression

@3cp Thoughts?

![meriyah](https://user-images.githubusercontent.com/31855118/119970296-22113800-bfe2-11eb-80e2-6da800c0b897.png)

**Comment by prantlf** [comment]
I wrote a benchmark to compare various parsers: https://github.com/prantlf/ecmascript-parser-benchmark#readme. Performance of Meriyah drops significantly when locations are enabled. The other parsers do not lose so much. Meriyah and Seafox are the fastest choices for a pure ESTree parser.
