### ISSUE TITLE
Incorrect exported for `export * as "string" ...`

### ISSUE THREAD

**Issue by fisker** [meriyah/meriyah#200]
```js
require('meriyah').parseModule('export * as "string" from "module"').body[0].exported
{ type: 'Identifier', name: 'string' }
```

Should be `Literal` instead.

**Comment by 3cp** [comment]
Interesting syntax. BTW, how to use the exported "string" later in the code?

**Comment by fisker** [comment]
`Import "string" as foo from "foo"` not sure if it works for javascript, this is designed for wasm, I think.

**Comment by fisker** [comment]
Seems `meriyah` don't support this syntax above either. Babel added support for it last year. https://babeljs.io/blog/2020/10/15/7.12.0#imports-and-exports-with-string-names-12091httpsgithubcombabelbabelpull12091

**Comment by fisker** [comment]
This syntax enabled by default in babel later https://github.com/babel/babel/pull/13195

> This syntax is effectively stage 4. It didn't go through the proposals process

**Comment by sosukesuzuki** [comment]
This syntax is added to ECMAScript by https://github.com/tc39/ecma262/pull/2154

**Comment by sosukesuzuki** [comment]
Usecase: https://github.com/WebAssembly/esm-integration/issues/39

**Comment by fisker** [comment]
@sosukesuzuki Only `imported` and `exported`? Does it allow `local` use string?

**Comment by 3cp** [comment]
```
ExportSpecifier:
  ModuleExportName
  ModuleExportName as ModuleExportName
```

The spec means following?
```
export "string";
export "string" as "string2";
```

**Comment by 3cp** [comment]
ModuleExportName is either Identifier or string Literal

**Comment by sosukesuzuki** [comment]
`ExportSpecifier.local` can be a string literal when only `from` clause exist.

```js
// invalid
export { "string" as "string2" };

// valid
export { "string" as "string2" } from "mod";
```

**Comment by 3cp** [comment]
@fisker double check with you. I don't think meriyah implemented "IsStringWellFormedUnicode", right?

"IsStringWellFormedUnicode" checks UTF-16 unpaired surrogate.

```
ModuleExportName : StringLiteral
• It is a Syntax Error if IsStringWellFormedUnicode(the SV of StringLiteral) is false.
```

**Comment by fisker** [comment]
> I don't think meriyah implemented "IsStringWellFormedUnicode", right?

I don't know, I'm not familiar with the parser.

**Comment by fisker** [comment]
Maybe we can drop Node.js 18, use `String#isWellFormed`?

**Comment by fisker** [comment]
polyfill seems short to me too https://github.com/zloirock/core-js/blob/0ff7e30a134f8ba1978e749e0b195d6c2be3fd78/packages/core-js/modules/es.string.is-well-formed.js#L12

**Comment by sosukesuzuki** [comment]
In a strict implementation, yes, because ModuleNameString must be a USVString.

**Comment by 3cp** [comment]
> Maybe we can drop Node.js 18, use `String#isWellFormed`?

Perfect 😄

**Comment by 3cp** [comment]
Meriyah got something for validating identifier. I probably just implemented it for string, like the polyfill.
