### ISSUE TITLE
Incorrect `.loc.start.column` for node inside return statement

### ISSUE THREAD

**Issue by bartosz-k** [meriyah/meriyah#207]
In example `function f(){return a(b)};` an incorrect `.loc.start.column` for `CallExpression` is generated. `column` for whole `CallExpression` is higher than `column` for `callee` subnode.

**Comment by 3cp** [comment]
That code mistake was not covered by our unit tests :-(
There are other bugs I want to work on before releasing a new version. Might take 2 or 3 weeks.
Cheers!

**Comment by bartosz-k** [comment]
Great, thx!

**Comment by 3cp** [comment]
Released v4.2.1.
