### ISSUE TITLE
es2022 support

### ISSUE THREAD

**Issue by aladdin-add** [meriyah/meriyah#214]
- [x] * Class Fields ([Private instance methods and accessors](https://github.com/tc39/proposal-private-methods), [Class Public Instance Fields & Private Instance Fields](https://github.com/tc39/proposal-class-fields), [Static class fields and private static methods](https://github.com/tc39/proposal-static-class-features))
- [x] * [RegExp Match Indices](https://github.com/tc39/proposal-regexp-match-indices)
- [x] * [Top-level await](https://github.com/tc39/proposal-top-level-await)
- [x] * [Ergonomic brand checks for Private Fields](https://github.com/tc39/proposal-private-fields-in-in)
- [x] * [Class Static Block](https://github.com/tc39/proposal-class-static-block)
- [x] * Arbitrary module namespace identifier names[https://github.com/tc39/ecma262/pull/2154]

**Comment by aladdin-add** [comment]
TLA has been supported,
class fields is still in next => need be enabled by default.

**Comment by julianjensen** [comment]
I see that top-level `await` has been checked above. Not sure if it's still in the works or not but, just in case, I thought I'd post this here to make sure that this is an upcoming feature and not a bug. Currently, `for await` when used as a top-level `await` is failing on version 4.2.1.

```
import { parse } from 'meriyah';

const parseExample = ( name, source ) => {
    try
    {
        parse( source, { module: true, next: true });
        console.log( `PASS: ${name}` );
    }
    catch
    {
        console.warn( `FAIL: ${name}` );
    }
};

parseExample( `async function with 'for await'`, `async function x() { for await ( const a of b ) console.log( 'Works!' ); }` );
parseExample( `top-level 'await'`, `await topLevelAwaitFunction( 'Works' );` );
parseExample( `top-level 'for await'`, `for await ( const a of b ) console.log( 'Also breaks' );` );
```
The above outputs:
```
PASS: async function with 'for await'
PASS: top-level 'await'
FAIL: top-level 'for await'
```

**Comment by 3cp** [comment]
test262 class-fields-private-in ([Ergonomic brand checks for Private Fields](https://github.com/tc39/proposal-private-fields-in-in)) is supported.
