### ISSUE TITLE
Missing tokens for JSXText

### ISSUE THREAD

**Issue by golopot** [meriyah/meriyah#216]
When parsing this JSX,
```
<a>123</a>
```
, there is no token corresponding to `123`.

**Code:**
```js
const meriyah = require("meriyah");

const tokens = [];
const source = `<a>123</a>`;
const ast = meriyah.parse(source, {
  jsx:true,
  onToken(type, start, end, loc) {
    tokens.push({
      type,
      value: source.slice(start, end),
      range: [start, end],
    });
  },
});

console.dir(tokens, {depth: null});
```

**Actual output:**

```js
[
  { type: 'Punctuator', value: '<', range: [ 0, 1 ] },
  { type: 'Identifier', value: 'a', range: [ 1, 2 ] },
  { type: 'Punctuator', value: '>', range: [ 2, 3 ] },
  { type: 'Identifier', value: 'a', range: [ 8, 9 ] },
  { type: 'Punctuator', value: '>', range: [ 9, 10 ] }
]
```

**Expected:**
The `123` part appears somewhere in the tokens.

**Comment by 3cp** [comment]
Lots of tokens in jsx didn't go through standard nextToken(). There should be more missing in some other cases.

**Comment by 3cp** [comment]
Same cause of #125. Would be fixed together.

**Comment by 3cp** [comment]
I am doing the same with setToken :)

Meriyah backtracks for two cases: 
1. the template re-scan "}" with "}text${" or "}text`".
2. jsx identifier scan "<a-b>", re-scan identifier "a" with jsx identifier "a-b".

Meriyah has manual scan for other jsx parts but doesn't backtrack or rewrite current token.

I am introducing a param for `setToken(value: Token, replaceLast = false)` to cover this two use cases.
