### ISSUE TITLE
Illegal async arrow function parameter error

### ISSUE THREAD

**Issue by mamaniv** [meriyah/meriyah#22]
Hi, I get `Illegal async arrow function parameter list` error

Here is the minimum code to reproduce the issue:

`
const sourceCode = "func('str', async param => {});"
`
`
meriyah.parse(sourceCode, {
          ranges: true,
          globalReturn: true
        });
`

BTW, I'm using Meriyah 1.3.4

Is it a known issue or is there any configuration that I missed?
Thanks.

**Comment by KFlash** [comment]
Just use Meriyah 1.3.5 :)

**Comment by mamaniv** [comment]
1.3.4 is the latest in npm

**Comment by KFlash** [comment]
I published 1.3.5 to NPM 1 hour ago.

![npm](https://user-images.githubusercontent.com/31855118/61381867-4a0bbc80-a8de-11e9-87f4-023892585691.png)

**Comment by mamaniv** [comment]
Thank you!
