### ISSUE TITLE
`for(x of~y);` is incorrectly rejected

### ISSUE THREAD

**Issue by bakkot** [meriyah/meriyah#226]
Found this with [a fuzzer](https://github.com/shapesecurity/shift-fuzzer-js), so feel free to ignore; this didn't come up in real code.

Issue is as the title says: `for(x of~y);` is a legal program, though not one you'd normally encounter, and meriyah rejects it.

**Comment by 3cp** [comment]
Should be easy to fix. The problem is the tokenizer didn't separate `of~`, as `for(x of ~y);` works fine right now.
