### ISSUE TITLE
TypeError: Do not know how to serialize a BigInt

### ISSUE THREAD

**Issue by gkucmierz** [meriyah/meriyah#230]
I think this library is not ready to parse `BigInt`.

**Comment by fisker** [comment]
Should allow `Literal.value` to be `null`, https://github.com/estree/estree/blob/master/es2020.md#literal

same for RegExp literal https://github.com/estree/estree/blob/master/es5.md#regexpliteral

**Comment by gkucmierz** [comment]
I am sorry, I think I opened this issue too early.

I am using [meriyah](https://github.com/meriyah/meriyah) in this repo: https://github.com/gkucmierz/instacode-app

And it looks like `BigInt` is handled correctly https://instacode.app

But what I am doing here is only I am searching for 1-level expressions, that are not calling `console` method in order to wrap them in `console.log` function.

**Comment by 3cp** [comment]
If this is a valid issue (which I cannot figure out by reading the thread), please provide simple sample code to produce the issue, plus expected behavior, thx.

**Comment by 3cp** [comment]
BigInt has no issue here. Literal.value is the BigInt value, the spec said use null for environment that doesn't support BigInt. There is no such environment right now.

BigInt value does mean the AST tree cannot be serialised with `JSON.stringify(ast)`. That's out of scope of meriyah.
