### ISSUE TITLE
Reduce bundle size by using `meriyah.esm.mjs` in favor of `meriyah.esm.js`

### ISSUE THREAD

**Issue by benmccann** [meriyah/meriyah#236]
Right now there is both a `meriyah.esm.js` and `meriyah.esm.mjs` that are distributed. These appear to be the same file:

https://github.com/meriyah/meriyah/blob/15f426f9871e923ec7396b5e35a33b976ed6c5c3/scripts/bundle.js#L18

Distributing the same file with two different names makes the npm bundle larger whereas if `meriyah.esm.mjs` were used exclusively the bundle size would be smaller

**Comment by 3cp** [comment]
When we enabled cjs and mjs files, the js files were kept for backwards compatibility in case users have explicitly used them.

I agree we need to clean the dist files up. But we prefer doing it together with a major version release, that would also allow us to remove more outdated files in current JS lands. For example the systemjs format files.

**Comment by fisker** [comment]
Fixed by #284
