### ISSUE TITLE
package name?

### ISSUE THREAD

**Issue by aladdin-add** [meriyah/meriyah#24]
"meriyah" is a sort of, emm.... awkward-sounding. do we want a better name?

"buntis" is built on the top of "meriyah", but it's a bit unrecoverable for users -- it's not in the group, and has a unrelated name. 😂

**Comment by KFlash** [comment]
@aladdin-add 'meriyah' is maybe awkard-sounding, but etablished now so can't change it I guess.

'buntis' is a stand-alone parser and not build on top of Meriyah. If you look at the source code of it, the differences are huge. They have mostly nothing in common

**Comment by KFlash** [comment]
Closing this as I think I answered the question.
