### ISSUE TITLE
static arrow function in class throws an error

### ISSUE THREAD

**Issue by Vexcited** [meriyah/meriyah#248]
Hi! That library is soo good, but I had one issue earlier..

With the following code:
```typescript
class o {
  static a = e => fetch(e)
}
```

or
```typescript
class o {
  a = e => fetch(e)
}
```

Meriyah throws:
```
[2:12]: Expected '('
```

Even though, when doing:
```typescript
class o {
  static a(e) { return fetch(e) }
}
```
it works.

Any idea if this is going to be supported ?

**Comment by 3cp** [comment]
You need to turn on "next" option.

We probably need to remove the option, or default it to true.
"next" was a thing a decade ago, now it's in every browsers.

**Comment by Vexcited** [comment]
Thanks you for the fast reply! That fixed the issue, thanks!
