### ISSUE TITLE
Add `ImportAttribute` for import attributes (stage 3 Estree)

### ISSUE THREAD

**Issue by aralroca** [meriyah/meriyah#253]
Now that runtimes like Bun supports macros and the proposal is in stage 3 it would be nice to support import attributes.

https://github.com/tc39/proposal-import-attributes

Example in TypeScript:
<img width="1724" alt="Screenshot 2024-03-19 at 22 14 21" src="https://github.com/meriyah/meriyah/assets/13313058/75c12ed7-8dd4-4ca0-be01-56fdd1c67ce8">

**Comment by 3cp** [comment]
## Note for implementation

https://github.com/estree/estree/blob/master/stage3/import-attributes.md

EStree which meriyah implements has different definition of this syntax.

**Comment by 3cp** [comment]
BTW I don't think the typescript screenshot is a correct reference :-)

The old (or current) typescript parser thinks that's the legacy with statement, not part of the import declaration. You can see they appear as two sibling nodes in the syntax tree.

**Comment by aralroca** [comment]
It will be great to replace the TypeScript parser that I used in this plugin with Meriyah, which is much faster! 

https://github.com/aralroca/prerender-macro

**Comment by 3cp** [comment]
I cannot guarantee a time frame for this feature as I don't have enough bandwidth on open source projects right now. But I will put it on my TODO list :)

**Comment by 3cp** [comment]
Bun has a native parser. Maybe you can talk to them to expose some APIs. It's probably not in extree syntax, but nothing beats Bun's performance.

> the parser in Bun is a Zig port of esbuild's parser.

**Comment by aralroca** [comment]
> Bun has a native parser. Maybe you can talk to them to expose some APIs. It's probably not in extree syntax, but nothing beats Bun's performance.
> 
> > the parser in Bun is a Zig port of esbuild's parser.

Yes, I have discussed it several times on discord but I really don't know if they have plans to do it in the short term. Maybe @Jarred-Sumner can confirm

**Comment by aralroca** [comment]
@3cp Is there any news on this? 😊 if I can help in contributing I am open although I am not familiar with it.

**Comment by 3cp** [comment]
Sorry I have not put on any effort. You are more than welcome to try.

**Comment by aralroca** [comment]
Maybe I'll take some time this coming week, any tips @3cp? I see that there is no CONTRIBUTING.md in the repo

**Comment by 3cp** [comment]
https://262.ecma-international.org/

Ecmascript spec defined all logic that a parser needs to follow. But it's a hard piece to digest.

The output new node shape is defined by estree spec.

Our code base is not hard to understand, the complexity is all the details in every method.

Have fun! 😃

**Comment by aralroca** [comment]
thanks for the tips @3cp, feel free to review the PR! I'm very glad to have the import attributes in Meriyah!

**Comment by 3cp** [comment]
@aralroca @fisker meriyah v5.0.0 is released. The reason for major release is that I moved some features out of "next" option, as they were landed in stage 4 or ecma spec now.

Also I found out how to find spec in stage4, it's in PRs to tc39/ecma262 repo.
https://github.com/tc39/ecma262/pull/3057/files

The spec is very details, we need to check our implementation against the spec :-)

**Comment by Tcjmd** [comment]
@3cp you also need to update the readme. It says support for ecmascript up to 2021

**Comment by 3cp** [comment]
Probably cannot say we supported 2023 or 2024.
We still have lots of gap to catch for latest ecma spec. We don't have enough time and contributors working here :-)

**Comment by fisker** [comment]
I didn't see v5 here  https://github.com/meriyah/meriyah/releases

Did we lost opportunity to fix https://github.com/meriyah/meriyah/issues/236?

**Comment by 3cp** [comment]
releases page is still manual for us. I need to fill it up.
I totally forgot #236 :(

**Comment by 3cp** [comment]
I will do another major release in near future for #236.
Our major number is still not big as Chrome, so we are fine :-)
