### ISSUE TITLE
Should not parse invalid code `import from 'foo'`

### ISSUE THREAD

**Issue by fisker** [meriyah/meriyah#258]
```js
import from 'foo'
```

should be invalid code.

**Comment by 3cp** [comment]
Interesting how did we miss that :)

**Comment by 3cp** [comment]
A missed check, quite simple to fix.
Also found out `import {} from 'foo'` is valid...

**Comment by fisker** [comment]
>  Also found out `import {} from 'foo'` is valid...

Yes, equals to `import 'foo'`

**Comment by 3cp** [comment]
v4.4.4 is released.
