### ISSUE TITLE
Weird context mutation

### ISSUE THREAD

**Issue by 3cp** [meriyah/meriyah#274]
https://github.com/meriyah/meriyah/blob/434279f78e90a6a8d4e5d891fc3b2b8414030c36/src/parser.ts#L4836

The two binary bits used there are Context.Strict and Context.Module, but the `<< 11` doesn't make sense here.

I tried to remove the whole thing, change that line to `validateFunctionName(parser, context, parser.token);`. All unit tests still pass.

@fisker could you help to have a look? I don't know if missed anything here.

**Comment by 3cp** [comment]
```

    context =
      ((context | modifierFlags) ^ modifierFlags) |
      ((state & 0b0000000000000000000_0000_01011000) << 18) |
      0b0000110000001000000_0000_00000000;
```

Found more, the `<< 18` doesn't make any sense either. the 01011000 is OptionsDirectives, OptionsJSX, OptionsLexical.
Left shifting 18 of them will become InYieldContext, InAwaitContext, InConstructor.

**Comment by 3cp** [comment]
> https://github.com/meriyah/meriyah/blob/434279f78e90a6a8d4e5d891fc3b2b8414030c36/src/parser.ts#L4836
> 
> The two binary bits used there are Context.Strict and Context.Module, but the `<< 11` doesn't make sense here.
> 
> I tried to remove the whole thing, change that line to `validateFunctionName(parser, context, parser.token);`. All unit tests still pass.
> 
> @fisker could you help to have a look? I don't know if missed anything here.

Got it, the code tried to turn on Context.InYieldContext when Context.Strict, and Context.InAwaitContext when Context.Module. But the logic is not needed now, because validateFunctionName checks `(Context.InAwaitContext | Context.Module)` and ` (Context.InYieldContext | Context.Strict)`.

**Comment by fisker** [comment]
小黄鸭调试法。
