### ISSUE TITLE
Performance improvement 

### ISSUE THREAD

**Issue by ghost** [meriyah/meriyah#281]
@3cp @fisker 

Performance can be improved if you reduce validation checks etc. 

as one example the regEx in keyword and contextuals can be optimized too a  e.g `expectKeyword` instead of `expect` and then validate

```ts
Function expectIdentifer(token,  text) {
if(token & Identifier && text === raw)
....
}
```

'raw` in this example will only match if not escaped.

Another optimization trick is to check if start of statement or expression. If source is start of expr. Skip validation and switch statements and parse expressions directly.

For comments issues. Track pos of token start, then in a printer or callback search for comments in the range after last token and before next token.

Don't do it in scanner. Avoid the callback.

You can also skip Prettier if you want to walk that line. Save info on the ast on first pass to avoid a second pass. Info like done in Prettier.
Then create your own pretty printer. 

Do a AST walk to strip extra info before anything if any calls from end-user to walk the AST or modify it. You still follow EStree . But you avoid all Prettier checks slow downs.

Want to skip Terser too? Need a second pass for it, but that's not part of optimization

**Comment by Tcjmd** [comment]
Also consider refactor lexer to use `charAt` instead of relying on `CodePoint`. 

Unicode is rare and no need this extra validation in number scanning, tokens, string etc.

You can do this validation outside the hot path when needed.

**Comment by Tcjmd** [comment]
Another option for escaped keyword to avoid the equal comparison to `raw` is to add a `escapedIdentifer' token and use e.g. 'isIdentifer(){}` or `IsEscapedIdentOrKeyword(){}`.

It's only edge cases anyway, but you avoid extra validations coz `escapedIdentifer' is only true in rare cases

**Comment by 3cp** [comment]
Thanks very much for ideas! Would you like to try to raise some PR(s)? :-) Please make PR small on an isolated change to ease the review.

Regarding `Unicode is rare and no need this extra validation in number scanning, tokens, string etc`, although meriyah implemented this long before I came here, I wish we didn't have the unicode validation in meriyah too :D, it alone enlarge mariyah quite a bit. If my memory is correct, test262 does enforce the check, so any compliant parser needs to support it.

**Comment by Tcjmd** [comment]
I can't do much with a broken collar bone atm, but maybe I can look into this next month.

Regarding Unicode. You know where it can appear. Identifiers.  String can't be any valid token and escaped `n` for BigInt etc should be invalid.

If Unicode starts with `/` in an identifier. Use a boolean.  Slice and validate. Return as e.g `EscapedIdentifer`.

For symbols you can split in a slow and fast path. Slice after iteration. Use boolean to mark if need slow path. JavaScriptCore have an smart way about that 

Validate identifier after slicing if the boolean has a positive value.

For other part of the scanner. No need to check Unicode.

**Comment by Tcjmd** [comment]
Another thing I noticed was the directive parsing. Maybe try to slice the text from source and see if it match within 12 chars plus quote. Then you know it's 1) string literal and 2) valid

There are more performant ways to solve this

**Comment by 3cp** [comment]
> broken collar bone

Sorry to hear that! Wish you a full recovery!
