### ISSUE TITLE
Comments 

### ISSUE THREAD

**Issue by ghost** [meriyah/meriyah#282]
@fisker  @3cp 

This parser can't output comments correctly. It's follow the EStree standard. It will lead to issues found in Prettier and Babel to mention a few. And it's also involves performance issues and regression.

Comments should be done in printing. Need to modify the loc and range for it to depend start and end of each token.

```ts

I'm a /* comment */ text
```

Here comment range is `5, 21`.  

In a printer scan this range for comment and attach it.

This example is simple and ofc need to optimize it, track if leading etc already printed etc.

One optimization trick is to use a boolean in the scanner / ast like `hasComment` to avoid comment scan if there is none, or  `hasSingleLine` to avoid validation between single and multi comment check before scanning.

For a `OnComment` callback it will lead to performance regression and hard to figure out where to put it. You can ofc add extra meta data on the returned comment to tell it belongs in mentioned range . 

That would require you to count printed chars to print it on correct place 

It's more complicated than this, but you get the hint.

**Comment by 3cp** [comment]
You do have issues with comments. Please try to make some PR(s) to improve it :-)
ESTree didn't define comment as a node, it thinks comment is not part of js code. So we don't have them in AST tree. Also it would be hard to try to add comment to AST as they can appear in some odd places of the code.

**Comment by Tcjmd** [comment]
My input didn't mention add comments as AST. That's impossible. Where to put them?

I pointed out how to get the comments while printing and slice the source text from token end to next token start and scan.

Further I explained that the comment callback kills perf and not accurate unless you got the token range.

**Comment by Tcjmd** [comment]
After some research I figured out it's possible to save comments on the AST and get them attached on correct loc with a printer func.

**Comment by kenbern** [comment]
@3cp 

Just a note that I believe comment handling should be the responsibility of the printer, not the parser (meriyah in this case).  Ideally, the parser would focus on generating the AST, leaving comment placement to the formatting stage. I know that inconsistent location tracking in most ESTree parsers makes this challenging (as the Prettier team can attest).

I've recently open-sourced a comment algorithm that I believe robustly addresses these comment placement challenges. It's available in my public code repository.  Feel free to adapt it for meriyah if you find it useful. The README file in the printer code repository provides a detailed explanation of the algorithm.
