### ISSUE TITLE
Rename default branch to `main`?

### ISSUE THREAD

**Issue by fisker** [meriyah/meriyah#287]
Everyone is using 😄

**Comment by 3cp** [comment]
Done :-)

**Comment by fisker** [comment]
Workflow need update https://github.com/meriyah/meriyah/blob/4a486784b7a6b035ffa6aef75baec506b9a5eb92/.github/workflows/node.js.yml#L8

Maybe other place else?

**Comment by 3cp** [comment]
Done.
