### ISSUE TITLE
Question about exporting json module

### ISSUE THREAD

**Issue by fisker** [meriyah/meriyah#289]
```js
export { default as a } from "foo.json" with { type: "json" };
```

is this valid?

**Comment by fisker** [comment]
I also found https://github.com/tc39/proposal-json-modules/issues/27#issuecomment-1200579318, maybe we should remove the check for `{type: "json"}`?

//cc @aralroca

**Comment by fisker** [comment]
https://github.com/babel/babel/discussions/14816#discussioncomment-3295018

**Comment by 3cp** [comment]
I think it's valid from the spec. I recall I tested with our PR, it worked as expected.

**Comment by 3cp** [comment]
I also questioned in our PR about the syntax error. Feel more natural with a runtime error.
The proposal is not in stage 4 yet, so it might change.

**Comment by fisker** [comment]
You are right, it's tested but this is confusing me  https://github.com/prettier/prettier/blob/957c6a736d1e7093e8d2712c53f768b4c0953301/tests/format/js/import-attributes/__snapshots__/format.test.js.snap#L304  maybe just because wrong error location?

**Comment by 3cp** [comment]
Unexpected "with" sounds like "next" option is off.

**Comment by aralroca** [comment]
```js
export { default as a } from "foo.json" with { type: "json" };
```

It is valid, with JSON what is not correct are the named exports, but the `default` is correct.

**Comment by fisker** [comment]
> Unexpected "with" sounds like "next" option is off.

It's on https://github.com/prettier/prettier/blob/3548153a4b33bd782b6b0f0ca0689bfddce7631c/src/language-js/parse/meriyah.js#L14

**Comment by 3cp** [comment]
Oh, just noticed it's re-export, not import. It's our bug.

**Comment by fisker** [comment]
I guess the following are not allowed

```js
export * as foo  from './foo.json' with {type: 'json'};
export {}  from './foo.json' with {type: 'json'};
```

**Comment by aralroca** [comment]
there are cases in the tests252 of the import attributes that sets the `export`:

- `/language/module-code/import-attributes/import-attribute-empty.js`
- `/language/module-code/import-attributes/import-attribute-key-identifiername.js`
- `/language/module-code/import-attributes/early-dup-attribute-key-export.js`
- `/language/module-code/import-attributes/import-attribute-key-string-double.js`
- `/language/module-code/import-attributes/import-attribute-key-string-single.js`
- `/language/module-code/import-attributes/import-attribute-many.js`
- `/language/module-code/import-attributes/import-attribute-trlng-comma.js`
- `/language/module-code/import-attributes/import-attribute-value-string-double.js`
- `/language/module-code/import-attributes/import-attribute-value-string-double.js`

In the case of json modules with exports there are no specific tests252, but the export has been adapted to the behavior of the import (only syntax error when named bindings).

**Comment by 3cp** [comment]
From proposal https://tc39.es/proposal-import-attributes/#sec-exports

export [ExportFromClause](https://tc39.es/ecma262/#prod-ExportFromClause) [FromClause](https://tc39.es/ecma262/#prod-FromClause) [WithClause](https://tc39.es/proposal-import-attributes/#prod-WithClause)opt ;

Sounds like they are all valid. But test262 didn't cover all the ExportFromClause for this feature.
There is no `export { ... } from "..." with {...}` in test262 at all.
