### ISSUE TITLE
How to handle future reserved keyword in function name/param without backtrace

### ISSUE THREAD

**Issue by 3cp** [meriyah/meriyah#296]
Future reserved keywords can be used as identifier, but ONLY in non-strict mode.

Valid code:
```js
function a(let) {}
```

In valid code:
```js
"use strict"; function a(let) {}
```

Meriyah can handle the above two cases.
BTW, the second commit in #295 handled escaped identifier like `l\u0065t` (let).

However, missed following tricky one:

```js
function a(let) { "use strict"; }
```
This line should fail with "Unexpected strict mode reserved word" at "let".

The strict mode turned on by "use strict" needs to be applied to function name and parameters too. Since meriyah doesn't do back-trace, this is very tricky to implement.

**Comment by Tcjmd** [comment]
Not so tricky. Use bitmask. If found in function body, set the bit. Pass through to primary expr and do a validation when parsing ident.
If in func arg. Pass bitmask to body in case found

**Comment by Tcjmd** [comment]
@3cp the code seems to exist already?

https://github.com/meriyah/meriyah/blob/main/src/parser.ts#L3786

It's on `parser.flags`.

But there are no validation of this in Primary expr where you parse  an ident. And I think the mask need to be unset if outside current scope.

You also need to handle nested scops, but I think it's already taken care of. Didn't check the code

**Comment by 3cp** [comment]
It looks like so. Probably just a bug that missed the edge case.
Meriyah code is not clean. We all jumped on here because of the performance :-) I have been clean up bugs, but am bit afraid to make big changes due to lack of understanding of existing code (and also the ecma spec itself).

Don't tell me you are writing JS parser with assembly...
Sounds like you got too much time to kill...

**Comment by Tcjmd** [comment]
@3cp I'm just experimenting :) I wrote basicly a parser/linter/minifier/code formatter in c / assembly language just for fun just to beat esbuild perf. 
But my project is not clean either. I plan to rewrite it in Js/typescript and go public so people can contribute, but it will build itself to c / assembly code.
Scheduled for end of this year. Maybe you can jump on that train?

**Comment by 3cp** [comment]
Good luck to you! Benchmark against oxc, and bun, instead of esbuild :)
If your tool emits standard ESTree, I will be interested. I use ESTree parser in other projects.

I considered to give up ESTree, so I can use oxc or swc. But that means lots of rewrite in my projects.

**Comment by Tcjmd** [comment]
@3cp I'm not using EStree and not exposing Ast for public. It's all internal 

Where is the parser code of oxc?

**Comment by 3cp** [comment]
https://github.com/oxc-project/oxc

**Comment by Tcjmd** [comment]
I can't find the parser code in any of the folders?

Anyway. Did you benchmark this against meriyha?

**Comment by Tcjmd** [comment]
@3cp I checked it out. Oxc seems to borrow from TS code.

Off topic.  For a good AST do not store text, only loc. For the AST type it should be an enum packed with necessary masks containing info about the node - line breaks, whitespace, Unicode, has comments before or after etc. 

Summary. It will be compact and only numbers. No need extra "node flag" as in TS. It's kills perf. See upcoming release plan for TS. They try to get rid of that mistake .

**Comment by Tcjmd** [comment]
@3cp I was mistaken. After looking into the code I found out that the code you try to implement already exist!!

https://github.com/meriyah/meriyah/blob/main/src/parser.ts#L3772

**Comment by Tcjmd** [comment]
@3cp I also tested your code example in the online playground and it fails as expected 

`function a(let) { "use strict"; }`

What's the issue here?

**Comment by 3cp** [comment]
My bad :-( Function declaration and function expression work well.

It was https://github.com/meriyah/meriyah/blob/5764ad7e0dd66a60ed735141c38174d4bb5ffef4/test/parser/expressions/arrow.ts#L550-L552

Two issues here:
1. arrow function expression missed that check.
2. tested unescaped form with arrow function, found out another issue, it failed with strange error.

```js
(let) => { "use strict"; }
```
This one fails with a different error.

```js
        // TC39 deemed "use strict" directives to be an error when occurring
        // in the body of a function with non-simple parameter list, on
        // 29/7/2015. https://goo.gl/ueA7Ln
        if (parser.flags & Flags.SimpleParameterList) {
          reportMessageAt(parser.index, parser.line, parser.tokenPos, Errors.IllegalUseStrict);
        }
```

The link https://goo.gl/ueA7Ln doesn't work. And current ecma spec has no mention of this error. I guess I need to remove it.

For No.1, need to fix arrow function expression.

**Comment by Tcjmd** [comment]
@3cp this code is messy, so ok to messy it up more?

https://github.com/meriyah/meriyah/blob/main/src/parser.ts#L7355

On this line you get two choices 

1. Do if check, check if ident and set flag as in func param list

2. Do it in primary expression while parsing ident. For perf use an `inArrow` bitmask or something.

If not arrow func, just unset the bitmask. I think that's done already in func body.

That's what I could figure out. För escape ident you seem to have an token for it

**Comment by Tcjmd** [comment]
@3cp my bad this time  because this code is bad.

You need to set a check here

https://github.com/meriyah/meriyah/blob/main/src/parser.ts#L7248

And also before all to 'parseArrparseArrowFunctionExpressio' where u see an ident involved in param list

**Comment by 3cp** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Strict_non_simple_params

**Comment by Tcjmd** [comment]
This works as expected?

**Comment by 3cp** [comment]
Yes, the error is expected.
Spec used different wording. https://tc39.es/ecma262/#sec-function-definitions-static-semantics-early-errors

**Comment by Tcjmd** [comment]
Can you remove the overflow of `if` conditions throughout the code? Many can be merged and simplified.
Easier to read the code if I try to help you out

**Comment by 3cp** [comment]
You can try PRs, I would love to review.

**Comment by kenbern** [comment]
@3cp As outlined in issue #305, I believe a fragment-based approach can effectively address the challenges you've encountered. This methodology offers a potential solution to the problems you've described."
