### ISSUE TITLE
Should I use this instead of cherow?

### ISSUE THREAD

**Issue by axefrog** [meriyah/meriyah#3]
I am working on an experimental project of my own, full-time. Couldn't stop building things if I tried! I know this is your experimental parser you've been working on, and that you're retired, but that you keep popping up and doing work on this stuff anyway, so I can only assume that you're doing this because you like doing it. As such, I'm uncertain what your plans are, given that this is published on NPM and seems to be fully configured for ongoing development. Your co-developer on Cherow doesn't seem to have a lot of time, from the activity I've been observing, and so I'm wondering if Meriyah is a case of you sort of taking the reins back to some extent. Due to the nature of my project, I'm not installing from NPM - I do my own custom form of bundling and haven't written support for NPM-installed packages at this stage, so I just grab the latest `cherow.esm.js` from `/dist` in the dev branch. What would you prefer I do, to support your own efforts as best I can? Because I'm doing a heavy amount of transpiling/bundling via Cherow, I'm hitting the odd edge case now and again, as my bug reports possibly suggest, so I'll be continuing to report these kinds of issues when they pop up, but whether I do so against Cherow or Meriyah makes little difference to me as long as it is getting the job done :-)

**Comment by axefrog** [comment]
By the way, I noticed I can test against Meriyah on NPM via RunKit. Example that shows the class fields issue I was testing with Cherow:
https://runkit.com/embed/zw0qyaosuoho

**Comment by KFlash** [comment]
Cherow's goal aimed to be open-source friendly and also have a source code that others could read and contribute to. That parser also followed the "*standard*" way of doing parsing. Start with '*A*' and continue all the way until you hit the '*Z*'.  All parsers out there are developed like that - even that one in V8. At some point you end up banging your head against the wall. Specially when you have to fix edge cases, memory usage, destructing and assignments and so on. And in the end you will find out that you have too many limitations so you can't fix the edge cases at all.  That's the stage of Cherow now :)

Meriyah is my experimental parser yes, and I'm not bound to any of the mentioned limitations. This parser are developed in a different way. More like a internal modular approach, and it's memory usage is reduced by half compared to Cherow. And it's also around 40% faster than the Cherow parser :)

The main goal with Meriyah is to support the specs 100%. Including all edge cases. And it does too except for the missing part of code that I haven't ported yet from my private code.

To make it clear. It's my retirement project that I'm going to work on and experiment with from time to time and it's future goal is to be used in the same way as Cherow. And what you should support? Meryah doesn't have any line & column tracking *yet*, and will not get that for awhile. Except for that it's 100% spec compat and I will be surprised if you find any odd edge cases. 

But in the end it's up to you what you want to support. You know what fits your needs best :)

**Comment by KFlash** [comment]
Regarding your class field issue and NPM. Current version on NPM doesn't have implemented class field support, but you could try the dev version from the night builds. This *is* supported with Meriyah and should work :) But still WIP so not all cases fails yet as they should.

Look at [this tests](https://github.com/meriyah/meriyah/blob/master/test/parser/next/public-fields.ts) and I think we can agree that class fields are working on Meriyah :)

**Comment by KFlash** [comment]
@axefrog Be aware if you enable class field parsing, you also enable decorator parsing :) See [this proposal](https://github.com/tc39/proposal-decorators).

Off topic. Ok I add you to this project?

**Comment by KFlash** [comment]
@axefrog This is  perf benchmark so you can see the perf differences. Acorn is really fast :)

![perf2](https://user-images.githubusercontent.com/31855118/57743503-df7cab80-76f7-11e9-9290-dcd7826558fa.png)

**Comment by axefrog** [comment]
Hey sorry for the slow reply. I tend to dive into my work and when I come up for air, several days have passed...

You've sold me - I've decided to switch to meriyah shortly. I think that while the goal of writing code in a way that makes it easy for others to modify is admirable, I actually left that camp a while ago when I realised that facilitating "standard" modes of thinking is often orthogonal to really pushing the state of the art forward. So I am all for your approach with meriyah, and while I know that - as a retirement project - you'll only be going at the pace that suits you, to me it still feels like the better option for my own project.

You wanted to add me to the project... if that helps you I guess? I don't have capacity at this stage to offer development support, but you can bet I'll continue to report any issues I encounter in the course of my own work.

**Comment by KFlash** [comment]
I'm in need of human feedback now on Meriyah. I ran several fuzzers and they are all running without issues, but I'm 100% sure there still exist edge cases I have missed. So glad to hear you will report here if you come across a odd edge case :)  

My next step now will be to optimize the code even further before I'm implementing scoping locations I guess, but that have to wait. I will be gone for 5 - 6 days from tomorrow my time.

The internal modular approach is really simply. Let's say you  create a identifier and you want a computed value after it. Like `foo[bar]`. All you have to do is to create the identifier and use the member expr directly and it works. You skip a lot of validations that way, and you also avoid going down the `Assignment expr` path until you reach `primary expr` as in other parsers. 

I can also add there is no lookahead or backtracking in Meriyah.

**Comment by KFlash** [comment]
@axefrog The performance is actually better in real world parsing comparing to other parsers. 
I think @nchanged can testify on that?

**Comment by nchanged** [comment]
Here here :) stability, speed and memory consumption is impressive

**Comment by axefrog** [comment]
Just switched my code to drop Meriyah in place of Cherow. All fine, though currently my hottest paths are external to the parser, so I can't report on performance differences at this stage. I imagine this will change sooner or later, as I'm using Cherow (now Meriyah) in my bootstrapper, which isn't overly efficient, but which I needed to facilitate my current stage of development. I'll likely be taking what I'm doing right now and using it to emit a new bootstrapper/bundler that will be a lot more efficient. I'll also be heavily using the parser internally within the main runtime, as the code is designed to rewrite itself as runtime state evolves, and this involves a lot of automatic code (re)generation and the parser is an important part of that process.

**Comment by KFlash** [comment]
@axefrog I'm closing this for now.

**Comment by KFlash** [comment]
@axefrog I remember one of your issue tickets from Cherow regarding location tracking. I'm in the process of implementing ranges on each AST node now. Is it sufficient for now? 

Because I'm retired I'm not taking any shortcuts anymore, and the ranges implementation is some tricky piece of shit to fix. Totally different than what's done in other parsers, but at least I maintain the performnance :)

You can track the progress of this implementation soon because I'm going to open a PR for it due to it's complexity.

**Comment by axefrog** [comment]
I will need location tracking, but not for a while as it'll be used in an area of my code that I'm not working on at the moment.

I wholeheartedly support doing things properly over rushing them out the door. I've been working on my project full time for several years now, and getting it right has always taken absolute precedence over getting it done inside some arbitrary timeframe.

**Comment by KFlash** [comment]
Ok. But expect a little performance loss when ranges are used. There is no way I can avoid it, but I managed to reduce a huge loss of performance.

**Without ranges:**

![withoutloc](https://user-images.githubusercontent.com/31855118/58447064-c501f380-8135-11e9-81d7-afa5db306c4c.png)

**With ranges:**

![withloc](https://user-images.githubusercontent.com/31855118/58447079-d0551f00-8135-11e9-8803-6128a048f800.png)

**Comment by axefrog** [comment]
Makes sense. 👍

**Comment by futagoza** [comment]
@KFlash If ranges were made optional (e.g `options.ranges = false`), would it help to keep performance when ranges aren't required, or would that still add a performance hit due to the conditional check?

**Comment by KFlash** [comment]
@futagoza ranges are optional. Or at least it will be. Performance will suffer regardless, because of this, but the way I'm implementing this - passing start values as function args - the performance loss is minimal. 
My first attempt was to pass the end position as well, but too much conditional checks and  branching involved. That again killed performance.

Expect a 20ms performance difference when parsing larger libraries with ranges on, but still faster than Cherow and other parsers out there.

**Comment by KFlash** [comment]
@futagoza @axefrog Within a day I guess the ranges will be merged into Master branch. It have been implemented now, but I need to optimize this. 

**Note:** Because of the internal modular approach I'm using - the location tracking should be faster because the code are only executed once needed. Not like in a ordinary parser :)

**Comment by KFlash** [comment]
@futagoza @axefrog Ranges have been implemented, and the performance loss is minimal without ranges. 

**Without ranges:**

![withoutloc](https://user-images.githubusercontent.com/31855118/58669569-44c6d280-836f-11e9-8818-01f72f524a1f.png)

**With ranges:**

![withloc](https://user-images.githubusercontent.com/31855118/58669577-4abcb380-836f-11e9-9863-1e45d2e095f8.png)

**Comment by axefrog** [comment]
Nice work! For a retiree, you sure work fast ;)

**Comment by KFlash** [comment]
Until now, Cherow has been the fastest parsers, and actually it's hard to beat it's performance. This benchmark results give you a qlue about the differences between Cherow and Meriyah when it comes to performance.

The first results are with location tracker.

![yup](https://user-images.githubusercontent.com/31855118/58738467-748ddd00-8438-11e9-934e-b934624d24dd.png)

**Comment by KFlash** [comment]
@axefrog Meriyah REPL: https://meriyah.github.io/meriyah/
