### ISSUE TITLE
Optimize descKeywordTable using bitmasks

### ISSUE THREAD

**Issue by kenbern** [meriyah/meriyah#305]
```ts
export const enum Token {
  // ... other enum definitions
}

const keywordFlags = {
  // Define flags for each keyword
  this: 1 << 0,
  function: 1 << 1,
  // ... other keywords with flags
};

export function getTokenFromKeyword(str: string): Token {
  const flag = keywordFlags[str];
  if (flag !== undefined) {
    return flag as Token; // Type assertion for safety
  }
  // Handle unknown keywords (throw error, return default value, etc.)
}
```

Explanation:
 * We define a new object keywordFlags with properties for each keyword.
 * Each property value is a bitwise flag, where a specific bit position represents a particular keyword.
   (e.g., this: 1 << 0 sets the first bit for the this keyword).
 * The getTokenFromKeyword function takes a string and uses it as a property key in keywordFlags.
 * If the property exists, it retrieves the corresponding flag value.
 * We perform a type assertion (flag as Token) to ensure the retrieved flag value is interpreted as a Token.
 * If the property doesn't exist, handle unknown keywords as needed (e.g., throw an error or return a default value).
Benefits:
 * Faster lookups compared to object properties due to bitwise operations.
 * More compact representation compared to a full object.

**Comment by 3cp** [comment]
There are more that 32 keywords to be mapped.

**Comment by kenbern** [comment]
Group them? I can look into an different approach

**Comment by kenbern** [comment]
@3cp  Consider using Symbol keys instead of string keys. Symbols are unique and avoid string conversion overhead during property access.

```ts
const THIS_KEYWORD = Symbol("ThisKeyword");
const FUNCTION_KEYWORD = Symbol("FunctionKeyword");
// ... define symbols for all keywords

export const descKeywordTable = {
  [THIS_KEYWORD]: Token.ThisKeyword,
  [FUNCTION_KEYWORD]: Token.FunctionKeyword,
  // ... define key-value pairs using symbols
};
```

You can also do precomputed Lookups (if applicable): If you have a specific set of keywords that are frequently accessed, consider precomputing a lookup map for those keywords during initialization. This avoids the overhead of looking them up dynamically in the table.

Note that Symbols are not supported in older environments. Ensure compatibility if this is a concern.

**Comment by kenbern** [comment]
If you don't like Symbols you can consider that accessing properties directly is generally faster than using bracket notation.

```ts
   export const descKeywordTable = {
  this: Token.ThisKeyword,
  function: Token.FunctionKeyword,
  // ... other keywords
};
```

 * Precomputed Lookup Map:
   * If you know the keywords that will be accessed frequently, create a separate object for faster lookups.

```ts
   const frequentKeywords = ['if', 'else', 'for', 'while'];
const frequentKeywordMap = {};
for (const keyword of frequentKeywords) {
  frequentKeywordMap[keyword] = descKeywordTable[keyword];
}

// Use frequentKeywordMap for common keywords, and descKeywordTable for others
```

 * Inline Caching:
   * If you need to access the same keyword repeatedly within a function, consider caching the result in a local variable.
```ts
   function someFunction() {
  const ifKeyword = descKeywordTable['if'];
  // ... use ifKeyword multiple times
}
```
Performance Considerations:
 * Property Access: Direct property access (e.g., descKeywordTable.if) is generally faster than bracket notation (e.g., descKeywordTable['if']).
 * Caching: Caching frequently accessed values can improve performance, but be aware of potential memory overhead.

**Comment by kenbern** [comment]
@3cp @fisker   instead of the current token code in Meriyah - a Fragment-Based Parser for Enhanced Performance is the best solution.

However I haven't seen this done in any open source projects.

It's a novel approach to parsing by partitioning the parser into specialized "fragments." 

This fragmentation strategy offers substantial performance improvements over traditional lexer-based methods.

Key Advantages:
 * Elimination of the lexer: By directly processing source code without an intermediary lexer, we can achieve significant performance gains.
 * 
 * Optimized performance: Fragmentation allows for tailored optimizations specific to each parsing context.
 * Accelerated token lookup: Direct token lookup within fragments is significantly faster than traditional lexer-based approaches.

Implementation Example: 

**Function Parsing

Consider a function as a composite of two fragments: statements and expressions. By isolating the token set to (,) {}, we can employ efficient bitmask operations for punctuation character identification and whitespace skipping.

Additional Benefits:
 * Performance optimization: The combined use of tables and bitmasks further enhances lookup speed and reduces memory consumption.
 * Data transfer: Information extracted from one fragment can be seamlessly integrated into other fragments using similar data structures.

Implementation Considerations:

Implementing this approach requires either a substantial overhaul of an existing parser like Meriyha or the development of a new parser from scratch.

**Comment by kenbern** [comment]
This fragment-based approach offers flexibility in output formats. It can be adapted to generate Abstract Syntax Trees (ASTs) or directly produce formatted code, eliminating the need for external tools like Prettier.

Moreover, by maintaining metadata about each fragment, incremental parsing can be achieved efficiently by reprocessing only the affected parts of the code.

**Comment by kenbern** [comment]
@3cp I hope to see this changes in the next mayor release of this project

**Comment by kenbern** [comment]
@3cp @fisker I forgot to mention that while arrow function parsing presents a challenge, a fragment-based approach can effectively address it using a recursive structure similar to Meriyah's. By incorporating a whitespace scanner that tracks line breaks, comments, and parent nodes, the parser can accurately process complex syntax.

For instance, consider parsing an array. The opening and closing brackets form the primary fragment. Comments appearing before the opening bracket would be associated with that fragment, while subsequent comments belong to different fragments. By processing the code from right to left and transferring metadata between fragments, the parser can capture essential information, such as line breaks and comments, equivalent to the output of tools like Prettier. 

This approach has the potential to rectify several fundamental issues encountered in Meriyah.

**Comment by kenbern** [comment]
@3cp  BTW. By storing references to fragments in a lookup table, we can efficiently traverse the parsed code structure. 

This approach obviates the need for costly type checks and validations commonly performed in tools like Prettier.

 Navigating an array-based structure is significantly faster than traversing an Abstract Syntax Tree (AST).

 I eagerly anticipate a major overhaul of Meriyah to incorporate these enhancements.

**Comment by 3cp** [comment]
> major overhaul of Meriyah

It would not happy. Nobody contributing here in free time has the much resource in dispose.

You'd better working on a new project, or use other parser. As I told you before, oxc, swc, bun parser all provided much better test262 coverage, plus native performance. You should switch to them if better performance and spec compliance are most critical to you.

People switch to a totally new implementation, in hope of flighting existing problems. But in reality, the new thing brings new unknown problems. Whether the new unknown problems are easier to deal with? That's a huge unknown. I'd rather deal with known issues with meriyah right now.

**Comment by kenbern** [comment]
Existing open-source parsers are unlikely to achieve the performance levels attainable through a fragment-based approach. 

My proposed methodology offers a potential performance increase of up to 40% for Meriyah, as demonstrated by the code examples provided in previous issues.

I have developed a proprietary tool utilizing this fragment-based approach that surpasses the performance of benchmarks like Bun and V8.

Due to time constraints and other commitments, I cannot undertake a full-scale rewrite of Meriyah. 

However, I encourage you to explore the provided code snippets for potential performance optimizations within this project if you have time

**Comment by 3cp** [comment]
Thanks very much for all the inputs!

Optimisations can wait till we got close to 100% test262 coverage + new ES2024 features. With current resource, not sure we can get there ever :-)

**Comment by kenbern** [comment]
@3cp  For the benefit of the open-source community, this  outlines a foundational approach to fragment-based parsing based on my previous examples. The provided code demonstrates the capability to produce formatted output and comments, and constant folding."

```ts

const TOKEN_TYPES = {
  WHITESPACE: 1 << 0,
  IDENTIFIER: 1 << 1,
  NUMBER: 1 << 2,
  STRING: 1 << 3,
  PUNCTUATION: 1 << 4,
  COMMENT: 1 << 5,
  KEYWORD: 1 << 6
};

const FRAGMENT_TYPES = {
  EXPRESSION: 'Expression',
  STATEMENT: 'Statement',
  FUNCTION: 'Function',
  // ... other fragment types
};

const PRECEDENCE = {
  // ... operator precedence
};

function getTokenType(char) {
  // ... determine token type based on character
}

function isWhitespace(char) {
  return (getTokenType(char) & TOKEN_TYPES.WHITESPACE) !== 0;
}

function isIdentifierStart(char) {
  // ... check if character is valid identifier start
}

function isIdentifierPart(char) {
  // ... check if character is valid identifier part
}

function parse(input, options = {}) {
  let offset = 0;
  let indentLevel = 0;
  let output = '';

  while (offset < input.length) {
    skipWhitespace(input, offset);
    const tokenType = getTokenType(input[offset]);

    if (isCommentStart(input, offset)) {
      const commentEnd = findCommentEnd(input, offset);
      output += input.substring(offset, commentEnd) + '\n';
      offset = commentEnd;
      continue;
    }

    const fragment = parseFragment(tokenType, input, offset, indentLevel);
    output += fragment.output;
    offset += fragment.length;
    indentLevel += fragment.indentChange;
  }

  return output;
}

function parseFragment(tokenType, input, offset, indentLevel) {
  // ... parsing logic for different fragment types
  // Use lookups, state machines, and recursive calls as needed
  // Handle expressions, statements, declarations, etc.
  // Build output string with indentation and formatting
  // Consider using a fragment stack for complex expressions
  return {
    type: fragmentType,
    value: // parsed value or object,
    output: formattedOutput,
    length: consumedLength,
    indentChange: indentationChange
  };
}

// ... other helper functions for parsing specific constructs

function printFragmentStructure(fragment) {
  // Recursive function to print fragment structure
  // ...
}

function parseArray(input, offset, indentLevel) {
  let state = 'start';
  let elements = [];
  let output = '[';
  let indentChange = 1;

  while (offset < input.length) {
    const tokenType = getTokenType(input[offset]);

    switch (state) {
      case 'start':
        if (tokenType === TOKEN_TYPES.PUNCTUATION && input[offset] === '[') {
          offset++;
          state = 'expectingElementOrEnd';
        } else {
          // Error: expected '['
        }
        break;
      case 'expectingElementOrEnd':
        if (tokenType === TOKEN_TYPES.PUNCTUATION && input[offset] === ']') {
          offset++;
          state = 'end';
        } else {
          const element = parseExpression(input, offset, indentLevel + 1);
          elements.push(element);
          output += element.output;
          offset += element.length;
          state = 'expectingCommaOrEnd';
        }
        break;
      case 'expectingCommaOrEnd':
        if (tokenType === TOKEN_TYPES.PUNCTUATION && input[offset] === ',') {
          output += ', ';
          offset++;
          state = 'expectingElementOrEnd';
        } else if (tokenType === TOKEN_TYPES.PUNCTUATION && input[offset] === ']') {
          offset++;
          state = 'end';
        } else {
          // Error: expected ',' or ']'
        }
        break;
      case 'end':
        output += ']';
        return {
          type: FRAGMENT_TYPES.ARRAY,
          value: elements,
          output,
          length: offset - startOffset,
          indentChange: indentChange
        };
      default:
        // Error: invalid state
    }
  }

  // Error: unexpected end of input
}


function parseIfStatement(input, offset, indentLevel) {
  // ... skip 'if' keyword
  offset += 2;

  // Parse condition
  const condition = parseExpression(input, offset);
  offset += condition.length;

  // Skip opening parenthesis
  offset++;

  // Parse condition expression
  const conditionExpression = parseExpression(input, offset);
  offset += conditionExpression.length;

  // Skip closing parenthesis
  offset++;

  // Parse then block
  const thenBlock = parseBlock(input, offset, indentLevel + 1);
  offset += thenBlock.length;

  let elseBlock = null;
  if (input[offset] === 'e') { // Simplified check for 'else'
    // Parse else block
    offset += 4; // Skip 'else'
    elseBlock = parseBlock(input, offset, indentLevel + 1);
    offset += elseBlock.length;
  }

  // Build output string with indentation and formatting
  let output = `if (${conditionExpression.output}) {\n${thenBlock.output}`;
  if (elseBlock) {
    output += `\n} else {\n${elseBlock.output}\n}`;
  } else {
    output += '\n}';
  }

  return {
    type: FRAGMENT_TYPES.IF_STATEMENT,
    value: // if statement object,
    output,
    length: offset - startOffset,
    indentChange: 0 // No change in indentation for if statements
  };
}


function parseExpression(input, offset, indentLevel) {
  // ... (existing code)

  // Constant folding logic without try-catch
  if (isConstantExpression(expression)) {
    const value = evaluateExpression(expression);
    if (isNaN(value)) {
      // Handle potential errors (e.g., division by zero)
      return {
        type: FRAGMENT_TYPES.ERROR,
        message: 'Constant folding error',
        // ... other error details
      };
    }
    return {
      type: FRAGMENT_TYPES.LITERAL,
      value,
      output: value.toString(),
      length: expression.length,
      indentChange: 0
    };
  }

  // ... (rest of the function)
}

function evaluateExpression(expression) {
  // ... (existing evaluation logic)
  // Handle potential errors by returning NaN or specific error codes
}

function evaluateArithmeticExpression(expression) {
  const operatorIndex = expression.indexOf('+');
  if (operatorIndex !== -1) {
    const left = evaluateArithmeticExpression(expression.substring(0, operatorIndex));
    const right = evaluateArithmeticExpression(expression.substring(operatorIndex + 1));
    return left + right;
  }
  // ... handle other operators
  // ... handle numbers and parentheses
  // Return NaN or specific error code if error occurs
}
```

**Comment by 3cp** [comment]
As I said before, please use PR if you want a change. Because nobody else would raise the PR for you.

**Comment by kenbern** [comment]
The provided code offers a concise overview of fragment-based parsing for reference. If anyone reading this issue ticket and have further interest in this approach.

I've shifted my focus to analyzing the Prettier codebase now .

Feel free to close this issue
