### ISSUE TITLE
Type `FieldDefinition` missing property `type`: 'FieldDefinition'

### ISSUE THREAD

**Issue by xuld** [meriyah/meriyah#31]
of version 1.6.1

Besides, why do you delete `export { Options, ESTree }` again in 1.6

**Comment by KFlash** [comment]
Thanks for the info! It haven't been always been me doing the Meriyah code. A few previous students of mine did some contribution. And that should answer your question why `export { Options, ESTree }` have been removed in v. 1.6.

They did more flaws so I'm actually doing a refactoring of the entire parser ATM. Soon after I'm done I will release a v. 1.6.2 with the fixes you mentioned.

**Comment by KFlash** [comment]
Pushed a v. 1.6.2 with a fix. My refactoring isn't done, but the code is stable and working as you can see from this fuzzer picture

![stable](https://user-images.githubusercontent.com/31855118/62612843-df78fa00-b93a-11e9-84d0-bd27762776ae.png)
