### ISSUE TITLE
Refactor and improve performance? 

### ISSUE THREAD

**Issue by kenbern** [meriyah/meriyah#316]
The parser should be refactored to gain better performance. It's very slow comparing to Bun and Esbuild. It should be redesigned so everything will be done in as few "pass" As possible to e. g. prevent AST walking. 

Both Bun and ESBuild does everything within a "two pass" to gain performance. This involves proper handling of scope, hoisted variables etc. 

Should also optimize for unnecessary branching, monomorphic,  object creation etc. 

Typescript now experimenting with some of the technics.

**Comment by 3cp** [comment]
We have told you again and again no plan to rewrite here because of nobody has interest or resource. What more you want to hear?

I have directed you to those native parsers like bun, swc, and oxc.

Esbuild is in go lang, not JS either.
It doesn't make any sense to compare performance of meriyah to native parsers.

**Comment by kenbern** [comment]
I see. Anyway I'm done with Meriya. Seems to be buggy too. Tried to use through my own parser code, but ran into this

```ts
parsing-demo.js:5:17 - Error: Unexpected token ')' . Expected ';'
   3 |   let message = "Hello";
   4 |   console.log(message)
-> 5 |   greetUser("Meriyah")) // Error: Extra closing parenthesis 
      |                 ^
   6 | }
   
Suggestion: Remove the extra closing parenthesis or check for missing opening parentheses. 

parsing-demo.js:10:14 - Warning: Unused variable 'unusedValue'
   8 |   let age = 30;
   9 |   let unusedValue = 42; // This variable is not used
->10 |   console.log(calculateAge(age)); 
      |              ^

Note: Manually specified type annotations detected. Type checking will use provided types. 
```
