### ISSUE TITLE
Stable and feature complete

### ISSUE THREAD

**Issue by KFlash** [meriyah/meriyah#33]
Meriyah is now stable and feature complete **and** can be used in production. 

99k unit tests should cover the most common cases.

The performance is **okay**. Twice as fast as the Acorn parser.

So from now on only bug fixes will be done if bugs exist, and new language features such as Stage 3 will be added soon as they are ready.

cc/ @axefrog @nchanged @aladdin-add @fkleuver

**Comment by KFlash** [comment]
![speed](https://user-images.githubusercontent.com/31855118/62829141-95896000-bc29-11e9-87f6-bff787be3fc1.png)

**Comment by axefrog** [comment]
@KFlash Great work. Much appreciated on my end :)

**Comment by KFlash** [comment]
@axefrog After replacing my old students with a new one I finally pulled this off :) Time to move on to other projects.

![students](https://user-images.githubusercontent.com/31855118/62829520-4267db00-bc32-11e9-9f39-59ea37b896ce.jpg)

**Comment by lawrence-dol** [comment]
Very good. What is the recommended way to obtain the final JS? It seems like the project only contains source artifacts and no builds. I really don't want to install everything needed to do the build just to use the code.

**Comment by leeoniya** [comment]
check out the dev branch /dist

https://github.com/meriyah/meriyah/tree/dev

**Comment by lawrence-dol** [comment]
Thanks @leeoniya! I was expecting this to be in the master branch, not dev. Never even occurred to me to look there.

**Comment by futagoza** [comment]
You can also use https://unpkg.com/meriyah

**Comment by aladdin-add** [comment]
for most users, it's recommended to use via npm;
```bash
npm i meriyah
```

```js
var meriyah = require('meriyah');
meriyah.parse(code, options);
```

maybe the docs can be improved. PRs are welcome! :)

**Comment by vintprox** [comment]
So, it's turbo and can be used in browser runtime? 😃

**Comment by KFlash** [comment]
Closing this info as it's stable.
