### ISSUE TITLE
Meriyah not consistent while lex number? 

### ISSUE THREAD

**Issue by kenbern** [meriyah/meriyah#330]
I was wondering how Meriyah scanning numbers. This code snippet was added in my parser code so seems to be something wrong with Meriyah.  My friend added it last night. 

```ts
// Handle cases like "1." and ".1" as valid numbers (for consistency with meriyah)
    if (value === '.' || (value.startsWith('.') && value.length === 1)) {
      return createToken(TokenType.Punctuator, '.', start);
    }
```

**Comment by 3cp** [comment]
meriyah has no issue parsing
```js
var a = 1.;
var b = .1;
```

**Comment by kenbern** [comment]
Ok. I will double check what's causing this. Our algorithm normally not mistaken. Could be something else trigger this mayne
