### ISSUE TITLE
Bug: Doesn't handle tdz

### ISSUE THREAD

**Issue by kenbern** [meriyah/meriyah#333]
The parser doesn't handle TDZ - Temporary Dead Zone - in scope and there are existing minor issues with shadowing.

**Comment by kenbern** [comment]
Most people only think TDZ is for let and const. However.  Temporal Dead Zone (TDZ) rules should also been enforced for class fields, preventing access to class fields before their declaration within the class constructor.

Esbuild, and bun doesn't handle this either, and other esteee parsers. V8 handle this.

**Comment by 3cp** [comment]
Code sample that meriyah cannot parse pls.

**Comment by kenbern** [comment]
This is more about execute in correct order etc. I will give you more details shortly. Need to finish my bitmask calculation with 62 possibly outcome and over 1 million combos in my head. 

For further info about the. Check out esbuild bug tracking and v8

**Comment by kenbern** [comment]
```ts
function tdzExample() {
  console.log(myVar); // ReferenceError: Cannot access 'myVar' before initialization
  let myVar = 5; 
  console.log(myVar); // Output: 5
}

tdzExample();
```

**Comment by kenbern** [comment]
@3cp, are you available to join the ecast team? I'll soon be unavailable due to my regular job, but the project needs maintenance. A basic parser and advanced pretty printer are already implemented. I'll do my best to extend and simplify the parser before I leave, adding features like chunking, incremental parsing, and error recovery.
Upon my return, I'll upload code surpassing eslint and terser, along with an improved TypeScript-like type system. I'm confident in handling complex issues with your feedback. Are you interested?

**Comment by 3cp** [comment]
I have zero interest. But wish you good luck with it.

**Comment by 3cp** [comment]
That example produced a runtime error, not parsing time error. You have wrong expectation what parser should do.

When you run in v8, the error happens after calling the function, aka runtime error.

**Comment by kenbern** [comment]
@3cp Sometimes I wonder about your knowledge. Why close the issue? 

scope tracking with TDZ (Temporal Dead Zone) resolution in meriyah parser using JavaScript-like syntax.

Example:
function example() {
  console.log(a); // TDZ error - 'a' is not yet initialized

  let a = 10;
  console.log(a); // Output: 10

  if (true) {
    let b = 20;
    console.log(b); // Output: 20
  }

  console.log(b); // ReferenceError - 'b' is not in scope
}

How to Handle in Parser:
 * Symbol Table: Maintain a symbol table (e.g., a stack or hashmap) to store variable declarations along with their scope information.
 * Scope Entry/Exit:
   * On encountering a block (e.g., function, if, for), create a new scope entry in the symbol table.
   * When exiting a block, remove the corresponding scope from the symbol table.
 * Variable Declaration:
   * When parsing a let or const declaration:
     * Add the variable to the current scope in the symbol table.
     * Mark it as "uninitialized" until the actual assignment occurs.
 * Variable Reference:
   * When encountering a variable reference:
     * Search for the variable in the symbol table, starting from the current scope and moving outwards.
     * If found and initialized, proceed.
     * If found but uninitialized, raise a TDZ error.
     * If not found, raise a ReferenceError.
Simplified Pseudocode (Conceptual):
function parse(code) {
  let symbolTable = []; // Stack to track scopes

  // ... other parsing logic ...

  function enterScope() {
    symbolTable.push({}); // New scope
  }

  function exitScope() {
    symbolTable.pop();
  }

  function declareVariable(name) {
    let currentScope = symbolTable[symbolTable.length - 1];
    currentScope[name] = { initialized: false };
  }

  function referenceVariable(name) {
    for (let i = symbolTable.length - 1; i >= 0; i--) {
      if (symbolTable[i][name]) {
        if (symbolTable[i][name].initialized) {
          return; // Variable is in scope and initialized
        } else {
          throw new Error("TDZ error"); 
        }
      }
    }
    throw new Error("ReferenceError"); 
  }

  // ... parsing continues, calling enterScope, exitScope, 
  // declareVariable, and referenceVariable as needed ...
}
```

**Comment by kenbern** [comment]
Good luck to you too ;)

**Comment by 3cp** [comment]
Meriyah, v8, all followed ecma spec.
ecma spec didn't say it's an early error (parsing time). So v8 didn't implemented as parsing error either.

Not in spec, not in test262 suit. The spec might not be perfect on this case. But we don't introduce different behaviour than spec intentionally.

You can open an issue on ecma spec itself.
