### ISSUE TITLE
Need to fix tdz in class (guide included) 

### ISSUE THREAD

**Issue by kenbern** [meriyah/meriyah#334]
You need to fix tdz in class parsing. 

Example:
```ts
class MyClass {
  constructor() {
    console.log(this.a); // TDZ error - 'a' is not yet initialized
    this.a = 10;
    console.log(this.a); // Output: 10
  }

  method() {
    console.log(this.a); // Output: 10 (assuming called after constructor)
    let b = 20;
    console.log(b); // Output: 20
  }
}
```

How to Handle in Meriyah Parser:

 * Symbol Table: Maintain a symbol table to track scopes, similar to the previous example. Additionally, we'll need to associate class members (properties and methods) with their respective class scopes.
 * Class Scope:
   * When parsing a class declaration, create a new scope entry in the symbol table specifically for that class.
   * Within the class scope, track:
     * Constructor: A special method for initialization.
     * Properties: Variables declared within the class (e.g., using this.a = ...).
     * Methods: Functions defined within the class.
 * Constructor:
   * Treat the constructor as a regular method but with special handling for property initialization.
   * Ensure properties are assigned before they're accessed within the constructor to avoid TDZ errors.
 * Property/Method Access:
   * When encountering this.propertyName or this.methodName:
     * Search for the property/method within the current class scope.
     * If found, proceed.
     * If not found, consider searching in parent classes (if inheritance is supported).
     * If still not found, raise an error.
Simplified Pseudocode (Conceptual):

```ts
function parse(code) {
  let symbolTable = []; 

  // ... other parsing logic ...

  function enterClassScope(className) {
    symbolTable.push({ 
      type: "class",
      name: className,
      constructor: null,
      properties: {},
      methods: {} 
    });
  }

  function exitClassScope() {
    symbolTable.pop();
  }

  function declareProperty(propertyName) {
    let currentClassScope = symbolTable[symbolTable.length - 1];
    currentClassScope.properties[propertyName] = { initialized: false };
  }

  function accessProperty(propertyName) {
    // ... search in current class scope and potentially parent classes ...
    // ... handle TDZ and ReferenceError as needed ...
  }

  // ... similar logic for methods ...

  // ... parsing continues, calling enterClassScope, exitClassScope, 
  // declareProperty, accessProperty, etc., as needed ...
}
```

**Comment by 3cp** [comment]
Same reasoning in #333.

**Comment by kenbern** [comment]
@3cp 我刚才已经说明并告知您这应该在解析器中修复。这并不重要，Esbuild 和 Bun 打算实现这个，V8 已经实现了。这有点像 AnnexB，您想怎么处理都可以。
我觉得您对我的语气有点咄咄逼人？我是在侮辱您吗？如果是那样的话，我很抱歉。现在我需要专注于我自己的项目和代码。如果您将来改变主意，并选择加入我的专家团队，我们随时欢迎您。

**Comment by 3cp** [comment]
Doesn't v8 still show it as runtime error? (did latest v8 head changed it to an early syntax error)

I also told you we don't want to implement it before ecma spec added it. I don't think my reasoning is anything personal. We are an parser trying to follow ecma spec, no reason to deviate because the spec isn't perfect.

The fix should start with an issue discussion on ecma spec. Not here.

**Comment by kenbern** [comment]
It's okay. 

Check out this readme and see if I'm qualified enough to open issues on this issue tracker. 

I'm on the task to finish my own parser.  Let's run a benchmark at the end of the day!! 

Check this out. My CV

https://github.com/kenbern/Ecast/blob/main/eprint/readme.md

**Comment by 3cp** [comment]
Now I am pissed off, because I don't think you ever read my reasoning.

> We are an parser trying to follow ecma spec, no reason to deviate because the spec isn't perfect.

Talk to ecma if you think there is a missing hole in the spec.

There is nothing you can get out from meriyah by arguing this issue here.

And you also ignored my question asking you to clarify v8 behaviour. You just keep talking about what you want to talk.

**Comment by kenbern** [comment]
I will talk to rcms about it. And I understand your reasoning. Important to be pixel perfect against existing sorts and test262. That's it. And Meriyah does a good job!

**Comment by kenbern** [comment]
@3cp My parser is up and you can safely use it as an reference if you are doubting about edge cases etc. 

I solved it all - even your issues with Meriyah. I extended it to support error recovery and I addressed the ESLint issue. 

All  ESLInt plugins should work seamlessly. 

I hope this can help you further in your journey to maintain Meriyah parser

Check this readme for detailed info

https://github.com/kenbern/Ecast/blob/main/eparse/readme.md

**Comment by kenbern** [comment]
I hope this serves as inspiration! I wasn't able to implement incremental parsing at this time due to other priorities. However, I am currently working on it and will also address the Prettier issue. The type system will be tackled next month.
The key takeaway is that this project adheres strictly to ECMAScript standards. I hope my code inspires others and contributes to a stronger open-source community.
