### ISSUE TITLE
bad error: `cannot use "await" as identifier inside an async function`

### ISSUE THREAD

**Issue by aralroca** [meriyah/meriyah#342]
This code:

```js
class Foo {
  #bar = async () => {
    if (
      target._isTargetExposed() &&
      (await target._initializedDeferred.valueOrThrow()) ===
        Target_js_1.InitializationStatus.SUCCESS
    ) {
      this.emit('targetcreated', target);
    }
  };
}
```

when parsed, it gives this error when it does not have any await that is an identifier...

```sh
[133:39-133:44]: cannot use "await" as identifier inside an async function
```

meriyah v6.0.1

**Comment by 3cp** [comment]
Meriyah tokenises "target" (and also "meta") specially as `Token.Target`, but it only has real effect on `new.target`.

"target" and "meta" have missing "IsExpressionStart" bit mask. There could be more bugs around these two, but we don't have any unit tests covering those edge cases.

This bug got exposed by the new feature in parsing await.

**Comment by 3cp** [comment]
6.0.2 is released.
