### ISSUE TITLE
Error TypeError: c2 is not a function

### ISSUE THREAD

**Issue by aralroca** [meriyah/meriyah#344]
I am getting this error when parsing this code with meriyah `6.0.2`:

```ts
import { type ESTree, parseScript } from 'meriyah';

const code = `import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function Counter({ name }, { state }) {
    const count = state(0);
    return /*#__PURE__*/ _jsxs("p", {
        children: [
            /*#__PURE__*/ _jsx("button", {
                onClick: ()=>count.value++,
                children: "+"
            }),
            /*#__PURE__*/ _jsxs("span", {
                children: [
                    " ",
                    name,
                    " ",
                    count.value,
                    " "
                ]
            }),
            /*#__PURE__*/ _jsx("button", {
                onClick: ()=>count.value--,
                children: "-"
            })
        ]
    });
}`;

parseScript(code, {
  jsx: true,
  module: true,
  next: true,
});
```

Error:

```sh
Error TypeError: c2 is not a function
```

<img width="633" alt="Screenshot 2024-10-14 at 23 09 29" src="https://github.com/user-attachments/assets/e1ad1d7e-30ed-4e9d-9469-bd1cebcb9580">

**Comment by 3cp** [comment]
I could not reproduce the error with plain node environment.

I assume you are using a bundler to run the code in a browser. Might be a bundler bug?

**Comment by 3cp** [comment]
The code is different from `meriyah.min.mjs` and `meriyah.umd.min.js`, must be minified by your bundler setup.

**Comment by 3cp** [comment]
Try turning off minimisation (or optimisation), to verify if it's a bug in minimisation.

**Comment by aralroca** [comment]
> I could not reproduce the error with plain node environment.
> 
> I assume you are using a bundler to run the code in a browser. Might be a bundler bug?

Yes, it's related to Bun build, which is what we use. Curiously it only fails in development, in production it works fine (luckily).
