### ISSUE TITLE
dynamic imports aren't parsed

### ISSUE THREAD

**Issue by nchanged** [meriyah/meriyah#4]
Any attempts to parse
```
async function bar(){
     await import("./oi")
}
```

Fails.

**Comment by KFlash** [comment]
Related to this https://github.com/meriyah/meriyah/issues/2  See the bottom of this list.

**Comment by KFlash** [comment]
I'm closing this :)

**Comment by KFlash** [comment]
@nchanged I consider this issue as solved now. See https://github.com/meriyah/meriyah/issues/2
