### ISSUE TITLE
Pointers for generating a small build

### ISSUE THREAD

**Issue by jdalton** [meriyah/meriyah#42]
Hi!

Thanks for putting so much into meriyah. I'm looking for pointers for generating a small build that only detects dynamic `import()` use _(possibly later expanding to `eval()` use)_.

**Comment by KFlash** [comment]
Not 100% sure what you are looking for, but the internals of Meriyah make everything possible, and are modular.  That means you can import only basic from the core and e. g. modify `parseStatementListItem` to something like this

```ts
export function parseStatementListItem() {
return parseIdentifier(parser, context, /* isPattern */ 0;
}
```
Then when you do this `parse('hello!');` it will only return a parsed identifier AST node. This haven't been documented, but it's how it's done in locale build as an alternative to a plugin system.

It's also possible to just clone the repo and remove the modules you don't need.

**Comment by nchanged** [comment]
@jdalton not sure what you mean tho.  Meriyah is a full-fledged parser, you can't just take something out. 

That's how you detect an `import expression`
```
if (node.type === 'ImportExpression') {
}
```

**Comment by jdalton** [comment]
@nchanged I'm curious if there's a way to create a more targeted build of meriyah that focuses primarily on dynamic `import()`. I'm looking to add this as a more thorough detection to a project but want to minimize the client side size cost of doing so.

**Comment by calebboyd** [comment]
@nchanged -- this is in line with your goals with fusebox too AFAICT - Basically having a parser that _only_ identifies `import(` `require(` and `import ...` and chews threw everything else. Any bundler or loader shim would benefit a lot from something like that.

**Comment by nchanged** [comment]
I guess you meant this part https://github.com/fuse-box/fuse-box/blob/master/src/analysis/fastAnalysis.ts

V4 uses it for parsing typescript , and yeah nothing can beat it, but I still rely on meriyah it parse JS

**Comment by KFlash** [comment]
Interesting... If anyone have a good idea for this or can send a PR, I will welcome it. 
As @nchanged knows - I'm now busy until next week with my upcoming TypeScript / Javascript parser for his fusebox bundler, so I can't fully focus on this issue ATM. 
[Buntis](https://github.com/buntis/buntis) are developed in the same way as meriyah, and I was thinking that it should be easy to implement some pointers etc because there are no lookaheads and backtracking - everything is modular internal.

**Comment by jeremy-coleman** [comment]
an ast generator isnt the tool for that job imo. Just do a line by line regexp looking for import( + ) , its a reserved keyword with 1 use, cant really mess that up

**Comment by jdalton** [comment]
@jeremy-coleman The problem is you don't want a false positive within regexes, strings, template string literals, single or multiline comments. Also you can have comments between `import`, `(`, and `)` so it's non-trivial to match with a regex.

**Comment by jeremy-coleman** [comment]
https://github.com/fuse-box/fuse-box/blob/master/src/analysis/tokenizer.ts has the regex's if you want to play around. I really cant imagine a scenario where stripping comments and looking for "import( would be wrong

**Comment by nchanged** [comment]
My parser works in all scenarios even with the comments inside
