### ISSUE TITLE
location annotation

### ISSUE THREAD

**Issue by jeremy-coleman** [meriyah/meriyah#43]
acorn and typescript output the line annotations as loc.line and loc.column, but meriyah just adds it as line and column. Even though this is a relatively simple thing to fix, in practice it's going to create a lot of bugs when trying to replace acorn. (I rewrote browserify to use meriyah yesterday, and this came up)

**Comment by KFlash** [comment]
Hi. Out of the box Acorn outputs both line and column node on the AST node. This is off by default in Meriyah, but you can use the `range` option to enable it. 
If you enable the `loc` option you will get a `loc` object equal to Acorn. 

```ts
"loc": {
    "start": {line: Number, column: Number}
    "end": {line: Number, column: Number}
  },
```
The only differences between Acorn and Meriyah when it comes to location tracking is the `ranges` option. It was a design choice due to performance.  Acorn output this on the AST node 
if ranges is set `"range": [Number, Number]`, but Meriyah set the start and end properties.

If you feel anything should be different, you are welcome to send a PR. I'm in the middle of stress testing my Typescript parser, so little busy until next week.

**Comment by jeremy-coleman** [comment]
i had to change error handles like this
```js
        this.message = err.message.replace(/\s+\(\d+:\d+\)$/, '');
		//this.message = '';
        this.line = err.line;
        this.column = err.column + 1;

        //this.line = err.loc.line;
        //this.column = err.loc.column + 1;
        
        this.annotated = '\n'
            + (file || '(anonymous file)')
            + ':' + this.line
            + '\n'
            + src.split('\n')[this.line - 1]
            + '\n'
            + Array(this.column).join(' ') + '^'
            + '\n'
            + 'ParseError: ' + this.message
        ;
    }
```
Without the change , it throws with err.loc.line is undefined. Changing to err.line fixes it. (This is with line: true)

**Comment by KFlash** [comment]
Ah! You was talking about the error reporting :) Yes. That's different because Acorn uses a loc object and created a new SyntaxError, but I'm [extending the SyntaxError class](https://github.com/meriyah/meriyah/blob/master/src/errors.ts#L350).

**Comment by jeremy-coleman** [comment]
putting them under .loc would make it possible to drop in as an acorn replacement for all the existing tools, i think it's something to consider?

**Comment by KFlash** [comment]
I get the point, and yes I'm agree that this could be changed. Is this something you can make a PR for? I think maybe it's an idea just to add a new option - `acorn` and store a boolean value on parser state and check if the value is set when throwing an error.

**Comment by jeremy-coleman** [comment]
```js
export class ParseError extends SyntaxError {
 public loc: {
 line: ParseError["line"],
 column: ParseError["column"]
}
  public index: number;
  public line: number;
  public column: number;
  public description: string;
  /*eslint-disable*/
  constructor(startindex: number, line: number, column: number, type: Errors, ...params: string[]) {
    const message =
      '[' + line + ':' + column + ']: ' + errorMessages[type].replace(/%(\d+)/g, (_: string, i: number) => params[i]);
    super(`${message}`);
    this.index = startindex;
    this.line = line;
    this.column = column;

 //maybe this is all it needs?   
  if(!this.loc)this.loc = {}
this.loc.line = line
this.loc.column =column

    this.description = message;
  }
}
```

**Comment by KFlash** [comment]
Did some changes and pushed to NPM. See if that helps you :)

**Comment by jeremy-coleman** [comment]
cool , thank you! I'll let you know in a just a sec

**Comment by jeremy-coleman** [comment]
Perfect.
before
![image](https://user-images.githubusercontent.com/25135855/64429371-d4250580-d083-11e9-9954-7db2b6b8e5ef.png)

after
![image](https://user-images.githubusercontent.com/25135855/64429336-b9eb2780-d083-11e9-9fd0-b3b503a6e298.png)

**Comment by KFlash** [comment]
Good to know it solved :) If you face other issues don't hesitate to open an issue. I always try to respond and solve the issues within 1 hour from the moment it's reported.

**Comment by jeremy-coleman** [comment]
Will do. I'm almost finished with this refactor of browserify, i'll send you a link when its done , maybe some good marketing for meriyah? ;p

**Comment by KFlash** [comment]
I guess so :) Do you need to do a massive refactoring to get it working with browserify?

I looked at the file and I can try to "copy" that error output for both Meriyah and Buntis soon after I have pushed to public a prototype of the TS parser.

**Comment by jeremy-coleman** [comment]
@KFlash ok-ish for now, got some follow up to do. everything is in tools, the src folder is a demo app.
https://github.com/jeremy-coleman/meriyahify-demo
