### ISSUE TITLE
Report start column of token, not end?

### ISSUE THREAD

**Issue by lawrence-dol** [meriyah/meriyah#47]
When an error is reported, the column number is that of the last character of the token parsed. It would be better if it was the first character.

**Comment by KFlash** [comment]
Same reply as in #46. You could use `column`, `startColumn` or `colPos`

**Comment by lawrence-dol** [comment]
@KFlash : I'd like to, but I am not set up with the tool chain for developing TS, so pragmatically, I've no realistic path to testing any changes. I could experiment with the generated JS, but that won't be useful as a direct PR, only as a reference as to what to change.

**Comment by lawrence-dol** [comment]
@KFlash

I changed the error to use the token's start line/column:

  function report(parser, type, ...params) {
      throw new ParseError(parser.index, parser.startLine, parser.startColumn, type, ...params); /*LD: Use start line/colum*/
  }

But that then reported the last character of the previous token. So I also update the start values until a non-blank character is found:

  function scanSingleToken(parser, context, state) {
      const isStartOfLine = parser.index === 0;
      let   firstNonBlank = false; /*LD:Test for first ascii-non-whitespace*/
      while (parser.index < parser.end) {
          parser.tokenPos = parser.index;
          parser.colPos = parser.column;
          parser.linePos = parser.line;
          const char = parser.currentChar;

          /*LD:Test for first ascii-non-whitespace*/
          if (!firstNonBlank) {
              if(char <= 0x20) {
                  parser.startColumn = parser.column + 2;
                  parser.startLine = parser.line;
                  parser.startPos = parser.index;
              } else {
                  firstNonBlank = true;
              }
          }

          if (char <= 0x7e) {
              const token = TokenLookup[char];
              switch (token) {
    ....

But notice the unexpected ` + 2` for `startColumn`; for some reason the column is always 2 behind at this stage. Otherwise, it seems to work as expected.

**Comment by lawrence-dol** [comment]
The fix was trivial, though I think the parser properties names are not very intuitive. Simply change the `report` function to use `linePos` and `colPos` thus:

````
  function report(parser, type, ...params) {
      throw new ParseError(parser.index, parser.linePos, parser.colPos, type, ...params);
  }
````

**Comment by lawrence-dol** [comment]
I think these two fields ought to be `tokenLine` and `tokenColumn`.

**Comment by lawrence-dol** [comment]
Also, it looks like some of the doc comments for the parser fields have become out of date. I don't think the descriptions all fit their current purpose, though I could be misunderstanding the code.

**Comment by KFlash** [comment]
@lawrence-dol I asked a friend of mine to fix this and push some changes. It should be on NPM anytime soon.

**Comment by KFlash** [comment]
I guess this is fixed now.

**Comment by lawrence-dol** [comment]
@KFlash : Yes, the change to use `linePos/colPos` is present in 1.7.2. I didn't check whether documentation comments have been updated and you may take the field name question under advisement.
