### ISSUE TITLE
Typescript parsing

### ISSUE THREAD

**Issue by KFlash** [meriyah/meriyah#48]
There are no plans to implement support for Typescript parsing in Meriyah.

You can use the [Buntis](https://github.com/buntis/buntis) parser if you need to parse `JS`, `TS` and `JSX` / `TSX`.

**Comment by lukeed** [comment]
Hey, I just noticed that Buntis was archived. Is the plan to include TS parsing in Meriyah?

**Comment by moroshko** [comment]
@KFlash It would be great to have TypeScript support. What's the best alternative for now? 
@lukeed What are you using to parse TypeScript?

**Comment by lukeed** [comment]
I'm still using `buntis`, even though it was recently deleted entirely – which is very disappointing.

**Comment by KFlash** [comment]
Eslint have it's TS parser, but I guess it's too slow? Note that Meriyah was more or less some code my students did in a project,.

For now Eslint is the only solution or Babel, but I'm working on the Escaya project - which is my own code. In the rewrite I'm doing and the preparations for v. 1.0 release I plan to add a factory function kind of plugin so you can replace AST in the format you want. 

I'm not there yet, but I may add some callback hooks that let you  add additional syntax such as TypeScript.

So if I get to this point, Escaya can be extended to accept TypeScript. But it's a question about time - time I don't have too much of ATM.

**Comment by lukeed** [comment]
From what I understand though, escaya cannot replace anything. It's using its own AST format which means all other tools cannot interop.

I've enjoyed watching you and your students' work develop, but can you please briefly mention why buntis was deleted? It was unique in its featureset _and_ was immediately useful. I am 100% supportive of exploring new avenues, but "replacing" buntis with escaya is a net loss (so far).

**Comment by KFlash** [comment]
Escaya uses it's own AST as you have seen in the code online because of improved performance. Code online is still a WIP. 
My current Escaya code is different, and will let you use plugins to output the AST you want. I'm still not there.

Attached image may give you an idea on how I plan it.

Some students deleted it as it was part of their project, and it was too much "edge cases" that couldn't be fixed as far as I know. 

![early_stage](https://user-images.githubusercontent.com/31855118/88448835-4fe29900-ce74-11ea-8fac-b4e69a423b65.png)

**Comment by lukeed** [comment]
Cool, thank you.

Looking forward to Escaya's progress 👍

**Comment by KFlash** [comment]
I will soon enough open a PR on the Escaya repo with the first draft of v. 1.0. Then you will get some more ideas. Still not there. 

For now Escaya is on a basic level where I work out all edge cases for recover and incremental mode. But parses JS just fine.

**Comment by lukeed** [comment]
Would you consider shipping an entry point that's a preconfigured set of plugins for the ESTree format? And/or the Babel format?

It could look like 
```js
import { parse } from 'escaya/estree';
import { parse } from 'escaya/babel';
import { parse } from 'escaya';
```

The first two extend the last, and this way you can avoid 100 faulty implementations of Escaya + ESTree floating around.

This way you can also focus on performance with the raw parser, and allow there to be _some_ overhead/perf loss thru the extensions.

**Comment by KFlash** [comment]
I will look at it when the times come, but there is a lot of things to consider and think through before I get so far.

E.g. the 'kind' property - known as 'nodeType' in the early only code - can never be changed.  It's a unique set of numbers that keep track of the AST nodes in the internal walker and incremental. Shouldn't be a problem because the 'kind' property is only there in recovery / incremental mode and no need to transform that AST to public because it's for the IDE.

Maybe better to open an discussion about this on the Escaya repo?

**Comment by lukeed** [comment]
Will do. I know it's very much a future task, if any, but just wanted to mention it. Thanks 👍

**Comment by KFlash** [comment]
I will also need to think about how to add diagnostic messages through plugins etc. 

I'm getting closer to the stage where I need to think through all this. Maybe I invite you to a private repo soon as I get there to see if you get a few ideas.

Incremental parsing code next on my TODO now.

**Comment by KFlash** [comment]
@lukeed opened this issue ticked https://github.com/escaya/escaya/issues/8

**Comment by KFlash** [comment]
@lukeed Look at [this gist](https://gist.github.com/KFlash/361a6f5a99ce1aa2a492bddca9d0fa03). This is how I temporary do it now in Escaya. Ideas how this can be turned into a plug-in?
