### ISSUE TITLE
Missing null property in bad character escape sequence (template)

### ISSUE THREAD

**Issue by KFlash** [meriyah/meriyah#55]
@GuyLewin  There is missing an `null` property in the Revised Template Literal parsing when it comes to bad templates. Try to parse this `f`\xg`;`. 

Is this something you can look into? I have a fix for this, but it need to be ported to 2.0. A workaround for now (*I think*) is just to add `context | Context.TaggedTemplate` to identifier parsing in primary expression

**Comment by GuyLewin** [comment]
Just to be sure, what property should equal `null`?
According to MDN, I saw that `cooked` should be `undefined` (even though its `null` in Acorn according to AST parser) - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#ES2018_revision_of_illegal_escape_sequences

**Comment by KFlash** [comment]
https://github.com/estree/estree/blob/master/es2018.md#template-literals

**Comment by KFlash** [comment]
It's all fixed in the v. 2.0 you have
