### ISSUE TITLE
Issues using with TypeScript: no exported member 'Errors'

### ISSUE THREAD

**Issue by jwhitmarsh** [meriyah/meriyah#58]
Firstly, thank you for this excellent lib! 

Here's the issue: 
```
node_modules/meriyah/dist/common.d.ts:2:10 -
error TS2305: Module '"../../../../../../../node_modules/meriyah/dist/errors"' 
has no exported member 'Errors'.

2 import { Errors } from './errors';
```

I think it's because the `Errors` enum is marked as `@internal` so it's not making to the dist build, so everything importing `Errors` is unhappy. 

I've solved this by setting `skipLibCheck: true` in my tsconfig (which might be a good thing to do in any case), but thought it was worth raising in case someone else comes across it.

**Comment by KFlash** [comment]
Hi. Glad to hear you liked this lib :) I removed the `@internal` and pushed a new release to NPM. Let's hope that solves the issue.

**Comment by jwhitmarsh** [comment]
Thanks for the quick response @KFlash, that works now :)
