### ISSUE TITLE
In Object pattern can we create 2 different objects for key and value

### ISSUE THREAD

**Issue by peeyush31** [meriyah/meriyah#60]
if the key is not specified then the value and left of assignment pattern is the same object
```js
// 1st case
var {x} = {}

//2nd case
var {y=10} = {}
```
In these cases the key is not defined:
 - 1st case the `key` and `value` are the same object
 - 2nd case the `key` and `value.left` the left part of assignmentPattern are the same object

As a consumer to the parser I have to add properties to the AST nodes as the nodes are same object they properties get automatically added.

It will be good if the parser supports this and some  other people might face a similar issue.

**Comment by peeyush31** [comment]
@KFlash I can create a PR if you are OK with this change

**Comment by KFlash** [comment]
Hi. If you want you can do an PR and add this changes as an option. As it is now Meriyah are following the ESTree specs, so changes like this has to be behind and option.

**Comment by KFlash** [comment]
@GuyLewin Do you want to look into this?

**Comment by aladdin-add** [comment]
closing, as it seems has been resolved. thanks!
