### ISSUE TITLE
es5 dist?

### ISSUE THREAD

**Issue by Llorx** [meriyah/meriyah#63]
IE11 is a non-deprecated browser and has problem with arrow functions and such. meriyah is really powerful under IE11 to parse ES6 scripts, but meriyah aslo has ES6 functionalities, so is impossible to make it run under IE11.

Is there any problem to also add a `es5` output along with all the dist outputs existing now? Typescript works pretty well with this option, so it should be easy to add (as long as don't has Proxies. Is the only thing that is impossible to translate to ES5, for obvious reasons).

Some libraries output multiple files (like this one), but they also add a `xxx.es5.js` one, for weird people like me that have to develop things for IE11 :-/

**Comment by KFlash** [comment]
Hi. This shouldn't be easy to solve. Could you send a PR with a new build that suites IIE11? 
My knowledge about IE11 ism't 100%, and I got some RL issues to solve that take all my time now.

**Comment by aladdin-add** [comment]
I can make a PR, but I don't have access to publish to npm. could you add me(weiran.zsd) as a maintainer? @KFlash

**Comment by aladdin-add** [comment]
just add es5+umd, and **no** es5+cjs+systemjs+esm... given we already have a large number of dist/* 😅

@Llorx make sense?

**Comment by KFlash** [comment]
@aladdin-add I think you already have NPM access

**Comment by aladdin-add** [comment]
great, thanks! I'll try it later.

**Comment by aladdin-add** [comment]
@Llorx just published v1.9.6, you can use:

```js
var meriyah = require('meriyah/dist/meriyah.umd.es5.js');
```

**Comment by Llorx** [comment]
Woah, so fast. Is not even monday haha.

Thank you! ^^
