### ISSUE TITLE
The future of Meriyah

### ISSUE THREAD

**Issue by KFlash** [meriyah/meriyah#64]
Meriyah was developed by some students of mine, but I had a helping hand in the project. The exam is over, but still Meriyah will be maintained. However. Be aware that there will be no huge changes to the source code except for updating with new features.

Meriyah **is** the fastest open sourced javascript parser, and that will never change :)

If anyone are interested to improve Meriyah's performance, you are welcome because there are space for improvements. 

Below is a benchmark result between my private parser and Meriyah  :)

![next](https://user-images.githubusercontent.com/31855118/72580161-215c9200-3916-11ea-9120-ce50223b3dc6.png)

**Comment by KFlash** [comment]
@Llorx Hard to do so because it has a different architecture, and why should it be needed, Meriyah is fast enough :)

**Comment by KFlash** [comment]
@Llorx Try search "seafox" on NPM

**Comment by qguv** [comment]
Looks like the Github project linked on the NPM page for seafox is still set to private. Any chance of releasing the source? @KFlash :blush:

**Comment by Llorx** [comment]
Oh, you pushed it to npm! Didn't noticed, my bad. You are the boss @KFlash

**Comment by KFlash** [comment]
@qguv It's private because the source code is a couple of levels higher up than average developer on GH, and I'm still experimenting with it. 

@Llorx Yeah I did a long time ago. I can try within a few days to fix a es5 output

**Comment by KFlash** [comment]
@qguv Here is an example on code complexity

![example](https://user-images.githubusercontent.com/31855118/73650933-4a26aa80-46be-11ea-8584-1f86a1b4555a.png)

**Comment by qguv** [comment]
@KFlash Aah, so at least some of the speedup of your private parser is from the careful use of bitmasks. Looks like it would be a very interesting read :slightly_smiling_face:

**Comment by KFlash** [comment]
@qguv Why not check your email? ;) Or click [on this link](https://github.com/KFlash/seafox/blob/master/src/seafox.ts)

**Comment by KFlash** [comment]
@qguv Did you read the source?

**Comment by qguv** [comment]
@KFlash I've been working all week and haven't gotten the chance. I'll take a look at the typescript ticket as soon as I can, probably next week.

**Comment by KFlash** [comment]
@qguv The source is public now.

**Comment by KFlash** [comment]
@Llorx I think seafox supports IE11 now

**Comment by Llorx** [comment]
Hm, I still see arrow functions in the code. IE11 don't support ES6 functionalities, that's why I asked for a "es5" output in the typescript compiler options, if possible.

Now that the project is public (yay), I'll do my own PR for you to check.

**Comment by KFlash** [comment]
@Llorx Is there any arrows inside this file "seafox.umd.es5.min.js"?

**Comment by Llorx** [comment]
@KFlash For some reason I was looking the `0.4.3` version. Perfect now ^^
