### ISSUE TITLE
should fail on invalid modifier

### ISSUE THREAD

**Issue by KFlash** [meriyah/meriyah#73]
This should fail `({static a(){}})`

cc /  @aladdin-add

**Comment by KFlash** [comment]
@aladdin-add time to look into this?

**Comment by aladdin-add** [comment]
emm... I don't think I have the knowledge to fix it.

an option is to suggest people to start using seafox, as I didn't see a large value of maintaining 2 packages.

**Comment by KFlash** [comment]
Ok. I   will try to look into it soon.

Btw. There is a lot of differences between Meriyah and Seafox. Meriyah have jsx and a lot of other things. So people can't just swap.

**Comment by KFlash** [comment]
@aladdin-add I'm closing this and will try to fix the issue soon.

**Comment by KFlash** [comment]
@3cp This has been fixed?

**Comment by 3cp** [comment]
I didn't.

**Comment by KFlash** [comment]
Then it's not fixed. So I reopen

**Comment by fisker** [comment]
> an option is to suggest people to start using seafox, as I didn't see a large value of maintaining 2 packages.

Quote from https://github.com/meriyah/meriyah/issues/73#issuecomment-609847336

@KFlash Can you explain relationship between `meriyah` and `seafox`? We don't want add similar parsers to Prettier. Which one should we use?

**Comment by KFlash** [comment]
Meriyah. Seafox is just experimental to see and understand what my students did wrong. Meriyah have support for jSX, comment extraction etc. Seafox doesn't support this.
