### ISSUE TITLE
Feature: syntax check only mode

### ISSUE THREAD

**Issue by davidbonnet** [meriyah/meriyah#76]
Meriyah enables checking the syntax but produces a full AST if the code is correct. A syntax check only mode could speedup the parsing process by not producing AST nodes at all.

@KFlash: Is this feasible? I could look into it if so.

**Comment by KFlash** [comment]
@davidbonnet yes, we could add this to the parser. I have no time now, but a PR is always welcome

**Comment by KFlash** [comment]
Any update on this?

**Comment by davidbonnet** [comment]
Not yet, still planned though.
