### ISSUE TITLE
Include additional parsers in the performance benchmarks

### ISSUE THREAD

**Issue by rattrayalex** [meriyah/meriyah#78]
Given that meriyah claims a high focus on performance and therefore a major reason someone might choose to use it would be performance, having the benchmarks provided at https://meriyah.github.io/meriyah/performance/ available is quite helpful – thank you!

They would be even more helpful if they included a broader array of competing parsers, such as Babel's, TypeScript's, and ESLint's (Espree).

It may also be helpful to include example output of one run of this data in the README, so users can tell more quickly what the performance profile is like.

**Comment by KFlash** [comment]
@rattrayalex Is this something you will add a PR for? I have no time this days to fix this.

**Comment by rattrayalex** [comment]
Nope – maybe somebody else can, or you can close this as wontfix.
