### ISSUE TITLE
Unterminated regular expression

### ISSUE THREAD

**Issue by 3cp** [meriyah/meriyah#79]
Found a bug on regexp when parsing latest [svelte](https://github.com/sveltejs/svelte).
Here is the minimum code that triggers the issue:
```js
var a = /[\u{FDD0}-\u{FDEF}]/u;
```
That unicode range troubled meriyah. Seafox also failed.

Use following script to show the Error:
```js
const {parse} = require('meriyah');
const code = `var a = /[\\u{FDD0}-\\u{FDEF}]/u;`;
const ast = parse(code);
```

Error output:
```
/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:188
      throw new ParseError(parser.index, parser.line, parser.column, type, ...params);
      ^

ParseError [SyntaxError]: [1:29]: Unterminated regular expression
    at report (/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:188:13)
    at validate (/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:2006:11)
    at scanRegularExpression (/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:1998:27)
    at scanSingleToken (/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:531:38)
    at nextToken (/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:359:22)
    at parseVariableDeclaration (/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:3080:11)
    at parseVariableDeclarationList (/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:3065:21)
    at parseVariableStatement (/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:3055:28)
    at parseStatement (/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:2607:22)
    at parseStatementListItem (/Users/huocp/playground/s/node_modules/meriyah/dist/meriyah.umd.js:2601:22) {
  index: 29,
  line: 1,
  column: 29,
  description: '[1:29]: Unterminated regular expression',
  loc: { line: 1, column: 29 }
}
```

**Comment by KFlash** [comment]
Meriyah uses native regexp validator. Same as used in V8 and NodeJs.  So this isn't a bug within the parser itself.

**Comment by KFlash** [comment]
It's an invalid RegExp. 

Test it with Acorn

https://astexplorer.net/#/gist/752883abca64abb7ef1eeae38b6e1fb5/6b8ba9f0497b046ea3755de58346834ab85b4e8e

**Comment by 3cp** [comment]
I see. Thx!
Svelte must has special toolchain to transpile it to support it in app.

**Comment by 3cp** [comment]
Sorry my mistake, I forgot the `/u`. It's `var a = /[\u{FDD0}-\u{FDEF}]/u;`, nodejs can parse it, so could the browser.

Meriyah cannot, seafox cannot.
babel parser and acorn can parse it.

Maybe just a missing flag `u` when passing it to native regexp validator?

**Comment by 3cp** [comment]
Looks like the case. Any reason for parsing twice? The first pass has no proper flags.
```js
function validate(parser: ParserState, pattern: string, flags: string): RegExp | null | Token {
  try {
    RegExp(pattern);
  } catch (e) {
    report(parser, Errors.UnterminatedRegExp);
  }

  try {
    return new RegExp(pattern, flags);
  } catch (e) {
    return null;
  }
}
```

**Comment by KFlash** [comment]
Seems like a bug. Do you want to look into an fix? I'm knee deep in another private project atm.

**Comment by KFlash** [comment]
@3cp Try latest Seafox and if it works for you now? If it does, could you copy the code to Meriyah? I'm very busy atm.

**Comment by 3cp** [comment]
Sure. I will look into this.

**Comment by 3cp** [comment]
I tried following, it works with existing unit tests and the added test for this issue.
 
```js
function validate(parser: ParserState, pattern: string, flags: string): RegExp | null | Token {
  // try {
  //   RegExp(pattern);
  // } catch (e) {
  //   report(parser, Errors.UnterminatedRegExp);
  // }

  try {
    return new RegExp(pattern, flags);
  } catch (e) {
    report(parser, Errors.UnterminatedRegExp);
    // return null;
  }
}
```

I really don't understand the existing implementation, it seems to imply there is a subtle difference between `RegExp(pattern)` and `new RegExp(pattern, flags)`, where first could pass but second will fail.
But no matter what's the difference, the existing unit tests didn't cover that case.

**Comment by 3cp** [comment]
Why test/parser/miscellaneous/pass.ts has an invalid escape `\l` in a regexp?
```
`for (var c, f; (/[+-\\l-]/u); ((class {}).with)) var i;`
```

**Comment by 3cp** [comment]
There are few more invalid in that file.

Tested in nodejs console
```
> /(?=)?/iu
Uncaught SyntaxError: Invalid regular expression: /(?=)?/: Invalid quantifier
```

**Comment by KFlash** [comment]
My  students added them, and I have been lazy to go through it. If they are wrong, just comment them out.
