### ISSUE TITLE
Code generation (printing)?

### ISSUE THREAD

**Issue by lazarljubenovic** [meriyah/meriyah#84]
I know that the primary goal of the project is parsing (and the fact that it's so fast and _actually_ compliant to the spec is amazing; great job!). 

However, I am evaluating parsers to use in a project where I manually construct the AST -- so I don't really need a parser, I need to build (and manipulate) the AST, and then print it in the end. Are there plans to support code generation / codegen / printing? Is meriyah a good choice for this, or should I look elsewhere? Any suggestions?

**Comment by KFlash** [comment]
Meriyah should works just fine with escodegen and other tools. If you was wondering if Meriyah 
should behave same as escodegen - I think that's out of the scope for this parser because it's a parser.

**Comment by KFlash** [comment]
However. My new project - which is also a parser, but includes error recovery, incremental parsing and it's own ECMAScript® 2021 compatible abstract syntax tree (AST) - I plan to develop some tools.

**Comment by lazarljubenovic** [comment]
Thanks for the quick responses. My questions have been answered, so I'm closing this.
