### ISSUE TITLE
No error recovery or loose mode to be added in Meriyah

### ISSUE THREAD

**Issue by KFlash** [meriyah/meriyah#86]
No error recovery or loose mode as known from Acorn will be supported by the Meriyah parser. 

However. I'm soon going to open-source a "work in progress" parser that does error recovery and also support incremental parsing. This is way different than Acorn loose or other similar implementations, and can be used i any editors.
Everthing is designed from "bottom up", and ESTree not supported. Escaya runs it's own AST that conforms 100% to the standard ECMAScript® 2020 (ECMA-262 10th Edition). 

The parser I'm going to release is also around 40 - 50% faster than Meriyah

**Comment by KFlash** [comment]
Demo of the upcoming Escaya parser can be found here https://escaya.github.io/escaya/

Click on the "recovery" check box for some fun :)

**Comment by leeoniya** [comment]
would it be difficult to compare Escaya to Lezer? i'm assuming they're pretty different since Lezer supports nested grammers and other stuff besides ecma.

**Comment by KFlash** [comment]
@leeoniya Sorry late reply. 2 different worlds. 

Escaya aim to have equal AST both in "normal mode" and "recovery / incremental mode", and follow the ECMA specs. So they can't be compared. 

You can see Escaya as Acorn loose on super powers that actually works.

Play with the Escaya demo and open the console log. You see how it works and the AST nodes that is recovered.
