### ISSUE TITLE
BigInt

### ISSUE THREAD

**Issue by neumatho** [meriyah/meriyah#93]
Hi,

If you using a really big number in hexadecimal format, e.g. this one taken from your unit test 0x12300000000000000000000000000000000n, then the value of the Literal node only get the value of 9 instead of the real number, which is 99022168773993092867842010762644549533696.

I think it is because your doing a parseInt on a number that have exponential included.

The type of the node is also BigIntLiteral, which should only be Literal according to the specification.

-Thomas

**Comment by KFlash** [comment]
Thanks for this info! This was done by some students of mine. Do you want to do a PR to solve it?

**Comment by neumatho** [comment]
Well, I was hoping that someone on the Meriyah team will fix it :-)

**Comment by KFlash** [comment]
cc/ @3cp Any insight in this issue?

**Comment by 3cp** [comment]
My PR didn't change the type BigIntLiteral to Literal. I will double check estree spec.

**Comment by neumatho** [comment]
Just want to be sure that the changes work. Note that the parser does different things depending if your giving a big number as a normal number or in hexadecimal. I think you may loose precision for hexadecimal. Please double check with the number given above.

-Thomas

**Comment by 3cp** [comment]
Yes, your case is added into the unit tests.

**Comment by 3cp** [comment]
Thomas, the `BigIntLiteral` is right in the spec, a sub class of `Literal`. https://github.com/estree/estree/blob/d1cb85c0da029f905d3ef1930cec26d836f9d73f/es2020.md#bigintliteral

**Comment by neumatho** [comment]
You're right it is a new interface, but the type does not change, like for regex literals: https://github.com/estree/estree/blob/d1cb85c0da029f905d3ef1930cec26d836f9d73f/es5.md#literal. They are also called Literal as type.

If you try a bigint with Acorn on https://astexplorer.net/, then you will see it is also called Literal.

**Comment by 3cp** [comment]
I see, you are right.
We probably need to double check all estree interfaces.

**Comment by 3cp** [comment]
@neumatho pls try v3.0.0.

**Comment by 3cp** [comment]
@neumatho the v3.0.0 was shipped with wrong dist files. Pls try v3.0.1.

**Comment by neumatho** [comment]
That seems to work.
