### ISSUE TITLE
Named export

### ISSUE THREAD

**Issue by neumatho** [meriyah/meriyah#97]
Hi,

It seems that Meriyah does not comply with the AST standard when having named export, e.g. **export * as x from 'a'**.

First of all, it creates a _ExportNamedDeclaration_ where it stored an _ExportNamespaceSpecifier_ in the _specifiers_ array. The last one is unknown according to the specifications. If you compare it to Acorn, which seems to do it the right way, then you should create an _ExportAllDeclaration_ and then set the _exported_ property to 'x'.

If you look at the specifications, then you will see that this is the correct way to do it:

https://github.com/estree/estree/blob/master/es2020.md#exportalldeclaration

-Thomas

**Comment by KFlash** [comment]
Cc @3cp

**Comment by 3cp** [comment]
This looks like a new change in syntax. https://github.com/estree/estree/issues/202

**Comment by 3cp** [comment]
FYI `@babel/parser` still does the old way like us. I will update our implementation.
