### ISSUE TITLE
Wrong directive

### ISSUE THREAD

**Issue by neumatho** [meriyah/meriyah#99]
Hi,

If you parse the expression **"valueOf" in __proto** with the Directives option enabled, then a directive property is added to the ExpressionStatement node, which is wrong. The directive property should only be added for "use strict" literals.

Meriyah also adds a BinaryExpression in the expression property, which is not legal according to the AST specification for directives. See https://github.com/estree/estree/blob/master/es5.md#directive

For these two lines:

```
"use strict";
"valueOf" in __proto
```

the tree looks like:

```
{
  "type": "Program",
  "sourceType": "script",
  "body": [
    {
      "type": "ExpressionStatement",
      "expression": {
        "type": "Literal",
        "value": "use strict",
        "raw": "\"use strict\""
      },
      "directive": "use strict"
    },
    {
      "type": "ExpressionStatement",
      "expression": {
        "type": "BinaryExpression",
        "left": {
          "type": "Literal",
          "value": "valueOf",
          "raw": "\"valueOf\""
        },
        "right": {
          "type": "Identifier",
          "name": "__proto"
        },
        "operator": "in"
      },
      "directive": "valueOf"    <!-- this one should be removed
    }
  ]
}
```

A fix could be that you in the _parseDirective()_ function when checking for the directive option, also test the node type stored in _expression_ variable and only add the directive property if it is a Literal.

-Thomas

**Comment by KFlash** [comment]
cc @3cp @aladdin-add
